Repository B3Partners/tailormap, pull requests merged in 2018-05, with the labels that each got.

#1025 Bug/rewrite simple filter slider
  viewer/src/main/webapp/viewer-html/components/SimpleFilterFilters.js
Labels: :bomb: bug, enhancement :+1:

#1028 Fixes #1027: check if grids object is not empty before applying filter
  viewer/src/main/webapp/viewer-html/components/AttributeList.js
Labels: :bomb: bug

#1026 Fix for Mantis#10820: checkbox CQL must be surrounded by parentheses …
  viewer/src/main/webapp/viewer-html/components/SimpleFilterFilters.js
Labels: :bomb: bug

#1031 Print with defined scale
  .gitignore
  .idea/workspace.xml
  viewer/src/main/java/nl/b3p/viewer/image/CombineWMTSUrl.java
  viewer/src/main/java/nl/b3p/viewer/print/PrintInfo.java
  viewer/src/main/java/nl/b3p/viewer/stripes/PrintActionBean.java
  viewer/src/main/webapp/WEB-INF/classes/log4j.properties
  viewer/src/main/webapp/WEB-INF/xsl/print/A3_Landscape.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A3_Portrait.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A4_Landscape.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A4_Portrait.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/FeatureReport.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/calc.xsl
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Map.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersMap.js
  viewer/src/main/webapp/viewer-html/components/AttributeList.js
  viewer/src/main/webapp/viewer-html/components/Print.js
Labels: enhancement :+1:

#1041 Bugfix: set scale to current scale when opening printwindow
  viewer/src/main/webapp/viewer-html/components/Print.js
Labels: :bomb: bug

#1040 Retrieve filter from SharedSessionData for downloading features via a…
  viewer/src/main/java/nl/b3p/viewer/stripes/DownloadFeaturesActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/SldActionBean.java
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
  viewer/src/main/webapp/viewer-html/components/AttributeList.js
Labels: enhancement :+1:

#1045 update dependencies and plugins
  pom.xml
Labels: build infrastructure, enhancement :+1:
