Repository B3Partners/tailormap, pull requests merged in 2018-07, with the labels that each got.

#1128 Fixes #1127: Created textfield filter
  viewer/src/main/webapp/viewer-html/components/SimpleFilter-config.js
  viewer/src/main/webapp/viewer-html/components/SimpleFilter-filters-config.js
  viewer/src/main/webapp/viewer-html/components/SimpleFilterFilters.js
Labels: featurerequest :+1:

#1126 calculate the new zindex of the popup when showing the detailswindow,…
  viewer/src/main/webapp/viewer-html/common/ScreenPopup.js
  viewer/src/main/webapp/viewer-html/components/Maptip.js
Labels: :bomb: bug

#1129 Hide externallink when clicking left mouse button
  viewer/src/main/webapp/viewer-html/components/ExternalLinks.js
Labels: :bomb: bug

#1130 Bug/help fixes
  viewer/src/main/webapp/viewer-html/components/Legend.js
  viewer/src/main/webapp/viewer-html/components/Search.js
Labels: :bomb: bug

#1131 fix saving the retrieveUploads and uploadDocument option value
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ApplicationTreeLayerActionBean.java
  viewer-admin/src/main/webapp/resources/js/application/applicationTreeLayer.js
Labels: :bomb: bug, viewer-admin

#1132 fix saving the retrieveUploads and uploadDocument option value [v5.2.x]
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ApplicationTreeLayerActionBean.java
  viewer-admin/src/main/webapp/resources/js/application/applicationTreeLayer.js
Labels: :bomb: bug, viewer-admin

#1105 Fix for wrong columns in fileupload
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/databaseupdate/DatabaseSynchronizer.java
  viewer-config-persistence/src/main/resources/scripts/oracle-fileupload.sql
  viewer-config-persistence/src/main/resources/scripts/postgresql-fileupload.sql
  viewer-config-persistence/src/test/resources/nl/b3p/viewer/util/testdata.sql
Labels: :bomb: bug, viewer-config-persistence

#1133 Fix for wrong columns in fileupload [v5.2.x]
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/databaseupdate/DatabaseSynchronizer.java
  viewer-config-persistence/src/main/resources/scripts/oracle-fileupload.sql
  viewer-config-persistence/src/main/resources/scripts/postgresql-fileupload.sql
  viewer-config-persistence/src/test/resources/nl/b3p/viewer/util/testdata.sql
Labels: :bomb: bug, viewer-config-persistence

#1134 Use Maven 3.5.4 on the Jenkins server
  Jenkinsfile
Labels: build infrastructure

#1136 Fixes erroneous drawn geometry when buffering geometry
  viewer/src/main/webapp/viewer-html/components/SpatialFilter.js
Labels: :bomb: bug

#1137 Fixed #1125: bring the clicked on window to front (and calculate the …
  viewer/src/main/webapp/viewer-html/common/ScreenPopup.js
  viewer/src/main/webapp/viewer-html/components/Maptip.js
Labels: :bomb: bug

#1142 Check if layer exists when traversing the tree [v5.2.x]
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
  viewer/src/main/webapp/viewer-html/components/LayerSwitch.js
  viewer/src/main/webapp/viewer-html/components/SelectionModule.js
Labels: :bomb: bug

#1143 Do a null-safe check, which account for null equality.
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/SimpleFeatureType.java
Labels: :bomb: bug

#1144 add icons and remove button
  viewer/src/main/webapp/viewer-html/components/DownloadWKT.js
Labels: enhancement :+1:

#1146 Fixed incorrect retrieval of components when parsing the query parame…
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
Labels: :bomb: bug

#1145 Fixed incorrect retrieval of components when parsing the query parame…
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
Labels: :bomb: bug

#1121 Refresh feature info after editing feature
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Event.js
  viewer/src/main/webapp/viewer-html/components/Edit.js
  viewer/src/main/webapp/viewer-html/components/ExtendedFeatureInfo.js
  viewer/src/main/webapp/viewer-html/components/FeatureInfo.js
  viewer/src/main/webapp/viewer-html/components/Maptip.js
Labels: enhancement :+1:

#1152 Bug/oracle drop if exists dont work
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/databaseupdate/DatabaseSynchronizer.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/databaseupdate/ScriptRunner.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/databaseupdate/UpdateElement.java
  viewer-config-persistence/src/main/resources/scripts/oracle-dropfileupload.sql
  viewer-config-persistence/src/main/resources/scripts/oracle-fileupload.sql
  viewer-config-persistence/src/main/resources/scripts/postgresql-dropfileupload.sql
  viewer-config-persistence/src/main/resources/scripts/postgresql-fileupload.sql
  viewer-config-persistence/src/test/java/nl/b3p/viewer/util/TestUtil.java
  viewer-config-persistence/src/test/resources/nl/b3p/viewer/util/testdata.sql
Labels: :bomb: bug, enhancement :+1:

#1166 Upgrade GeoTools 19.1 -> 19.2
  pom.xml
Labels: build infrastructure, dependencies

#1167 various dependency en maven plugin updates
  pom.xml
Labels: build infrastructure, dependencies

#1168 Bugs/mantis#11570 duplicate layers in legend
  viewer/src/main/webapp/viewer-html/components/CoordinateLinkWindow.js
  viewer/src/main/webapp/viewer-html/components/Cyclorama.js
  viewer/src/main/webapp/viewer-html/components/Legend.js
Labels: :bomb: bug

#1171 Make attribute printing more robust
  viewer/src/main/java/nl/b3p/viewer/stripes/PrintActionBean.java
  viewer/src/main/webapp/viewer-html/components/Print.js
Labels: enhancement :+1:, viewer

#1175 reinstate integration testing with oracle
  .jenkins/insert-fla-version.sh
  Jenkinsfile
  viewer-admin/src/test/resources/oracle.properties
  viewer/src/test/resources/oracle.properties
Labels: build infrastructure

#1173 test for the existence of uploads before trying to render a table [v5.2.x]
  viewer/src/main/webapp/WEB-INF/xsl/print/FeatureReport.xsl
Labels: :bomb: bug, viewer
