Repository B3Partners/tailormap, pull requests merged in 2018-08, with the labels that each got.

#1177 Fix spinner for downloadwkt button
  viewer/src/main/webapp/viewer-html/components/DownloadWKT.js
Labels: :bomb: bug

#1181 update tomcat version to 7.0.90 (test dependency)
  pom.xml
Labels: build infrastructure

#1183 Feat/extended edit
  viewer/src/main/webapp/viewer-html/components/Edit.js
  viewer/src/main/webapp/viewer-html/components/ExtendedEdit.js
  viewer/src/main/webapp/viewer-html/components/components.json
Labels: enhancement :+1:, viewer

#1190 Fixed #1187: load vectorlayer when snappingcontroller is finished loa…
  viewer/src/main/webapp/viewer-html/components/Edit.js
  viewer/src/main/webapp/viewer-html/components/ExtendedEdit.js
Labels: :bomb: bug
