Repository B3Partners/tailormap, pull requests merged in 2018-12, with the labels that each got.

#1281 Set Ext language when app language is NL
  viewer/src/main/webapp/WEB-INF/jsp/app.jsp
Labels: :bomb: bug

#1278 do not log WFS password when debug logging is enabled, also log passw…
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/ArcGISFeatureSource.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/ArcXMLFeatureSource.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/JDBCFeatureSource.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/WFSFeatureSource.java
Labels: enhancement :+1:, security

#1279 add manual GeoTools WFS test
  viewer/src/test/java/nl/b3p/viewer/stripes/GeoToolsWfsTest.java
Labels: build infrastructure, enhancement :+1:

#1284 add javadoc checking on the Jenkins server builds
  Jenkinsfile
Labels: build infrastructure

#1280 Feat/editting features
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/GeoServiceActionBean.java
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en_US.properties
  viewer-admin/src/main/webapp/WEB-INF/jsp/services/geoservice.jsp
  viewer-admin/src/main/webapp/WEB-INF/jsp/services/layer.jsp
  viewer-admin/src/main/webapp/resources/css/main.css
  viewer-admin/src/main/webapp/resources/js/application/applicationTreeLayer.js
  viewer-admin/src/main/webapp/resources/js/services/attribute.js
  viewer-admin/src/main/webapp/resources/js/ux/b3p/FilterableCheckboxes.js
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en_US.properties
  viewer/src/main/webapp/META-INF/context.xml
  viewer/src/main/webapp/viewer-html/common/ScreenPopup.js
  viewer/src/main/webapp/viewer-html/components/ConfigObject.js
  viewer/src/main/webapp/viewer-html/components/CurrentLocation.js
  viewer/src/main/webapp/viewer-html/components/Edit-config.js
  viewer/src/main/webapp/viewer-html/components/Edit.js
  viewer/src/main/webapp/viewer-html/components/ExtendedEdit.js
  viewer/src/main/webapp/viewer-html/components/SelectionWindowConfig.js
  viewer/src/main/webapp/viewer-html/components/Snapping-config.js
  viewer/src/main/webapp/viewer-html/components/Snapping.js
  viewer/src/main/webapp/viewer-html/components/components.json
Labels: enhancement :+1:, featurerequest :+1:

#1282 contactform component
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en_US.properties
  viewer/src/main/java/nl/b3p/viewer/stripes/ContactActionBean.java
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en_US.properties
  viewer/src/main/webapp/WEB-INF/jsp/app.jsp
  viewer/src/main/webapp/viewer-html/components/ConfigObject.js
  viewer/src/main/webapp/viewer-html/components/Contactform-config.js
  viewer/src/main/webapp/viewer-html/components/Contactform.js
  viewer/src/main/webapp/viewer-html/components/components.json
Labels: featurerequest :+1:, viewer, viewer-admin

#1285 Fixed JSdoc warnings
  viewer/src/main/webapp/viewer-html/common/viewercontroller/MapComponent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Event.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Extent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Feature.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Layer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Map.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/MapTip.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Tool.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoArcIMSLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoArcLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoComponent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoImageLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoMap.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoMapComponent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoTilingLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoTool.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoVectorLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoWMSLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/tools/FlamingoMeasureArea.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/tools/JSButton.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersArcIMSLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersArcLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersArcServerLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersImageLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersMap.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersMapComponent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersTilingLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersVectorLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersWMSLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/ToolMapClick.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/Utils.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/tools/OpenLayersDefaultTool.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/tools/OpenLayersIdentifyTool.js
Labels: enhancement :+1:

#1256 Feat/multiple projections support
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ApplicationSettingsActionBean.java
  viewer-admin/src/main/webapp/WEB-INF/jsp/application/applicationSettings.jsp
  viewer-admin/src/main/webapp/WEB-INF/web.xml
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/CRS.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/Application.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/databaseupdate/DatabaseSynchronizer.java
  viewer-config-persistence/src/main/resources/scripts/oracle-add_projection.sql
  viewer-config-persistence/src/main/resources/scripts/postgresql-add_projection.sql
  viewer-config-persistence/src/test/resources/nl/b3p/viewer/util/testdata.sql
  viewer/src/main/java/nl/b3p/viewer/image/CombineImageSettings.java
  viewer/src/main/java/nl/b3p/viewer/print/PrintInfo.java
  viewer/src/main/java/nl/b3p/viewer/stripes/BufferActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/CombineImageActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/FeatureInfoActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/PrintActionBean.java
  viewer/src/main/webapp/WEB-INF/xsl/print/A0_Landscape.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A0_Portrait.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A3_Landscape.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A3_Portrait.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A4_Landscape.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A4_Portrait.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A5_Landscape.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A5_Portrait.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/calc.xsl
  viewer/src/main/webapp/viewer-html/common/viewercontroller/MapComponent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersMap.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersMapComponent.js
  viewer/src/main/webapp/viewer-html/components/CurrentLocation.js
  viewer/src/main/webapp/viewer-html/components/Print.js
  viewer/src/main/webapp/viewer-html/components/StreetView.js
  viewer/src/test/java/nl/b3p/viewer/stripes/AttributesActionBeanTest.java
Labels: enhancement :+1:

#1286 Backports
  Jenkinsfile
  viewer/src/main/webapp/viewer-html/common/viewercontroller/MapComponent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Event.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Extent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Feature.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Layer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Map.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/MapTip.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Tool.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoArcIMSLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoArcLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoComponent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoImageLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoMap.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoMapComponent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoTilingLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoTool.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoVectorLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoWMSLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/tools/FlamingoMeasureArea.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/tools/JSButton.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersArcIMSLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersArcLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersArcServerLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersImageLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersMap.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersMapComponent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersTilingLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersVectorLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersWMSLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/ToolMapClick.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/Utils.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/tools/OpenLayersDefaultTool.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/tools/OpenLayersIdentifyTool.js
Labels: build infrastructure

#1288 Implemented simple page, doing some basic checks.
  viewer-admin/src/main/java/nl/b3p/viewer/admin/UpgradeCheck.java
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/AfterUpgradeActionBean.java
  viewer-admin/src/main/webapp/WEB-INF/jsp/admin/afterupgrade.jsp
  viewer-admin/src/main/webapp/WEB-INF/web.xml
  viewer-admin/src/main/webapp/resources/images/accept.png
Labels: enhancement :+1:

#1295 various bugfixes in FeatureStyle
  viewer/src/main/java/nl/b3p/viewer/image/FeatureStyle.java
  viewer/src/main/java/nl/b3p/viewer/image/ImageTool.java
Labels: :bomb: bug, featurerequest :+1:

#1299 various bugfixes in FeatureStyle
  viewer/src/main/java/nl/b3p/viewer/image/FeatureStyle.java
  viewer/src/main/java/nl/b3p/viewer/image/ImageTool.java
Labels: :bomb: bug, enhancement :+1:

#1259 Set color on featurestyle when a new CombineImakeWkt is created for a buffer otherwise color is always red
  viewer/src/main/java/nl/b3p/viewer/stripes/BufferActionBean.java
Labels: :bomb: bug, viewer

#1300 Set color on featurestyle when a new CombineImakeWkt is created otherwise color is always red [1259]
  viewer/src/main/java/nl/b3p/viewer/stripes/BufferActionBean.java
Labels: :bomb: bug

#1302 [5.2.x backport] CombineImageWkt refactoring
  viewer/src/main/java/nl/b3p/viewer/image/CombineImageWkt.java
  viewer/src/main/java/nl/b3p/viewer/image/FeatureStyle.java
  viewer/src/test/java/nl/b3p/viewer/image/CombineImageWktTest.java
Labels: :bomb: bug, enhancement :+1:

#1301 CombineImageWkt refactoring
  viewer/src/main/java/nl/b3p/viewer/image/CombineImageWkt.java
  viewer/src/main/java/nl/b3p/viewer/image/FeatureStyle.java
  viewer/src/test/java/nl/b3p/viewer/image/CombineImageWktTest.java
Labels: :bomb: bug, enhancement :+1:, viewer

#1305 Bug/agelfixes
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en_US.properties
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: :bomb: bug
