Repository B3Partners/tailormap, pull requests merged in 2018-10, with the labels that each got.

#1217 Bump tomcat version 7.0.90 -> 7.0.91
  pom.xml
Labels: build infrastructure

#1220 pass all variables (also for non-compact link)
  viewer/src/main/java/nl/b3p/viewer/stripes/ApplicationActionBean.java
Labels: :bomb: bug, Hacktoberfest :beers:

#1219 pass all variables (also for non-compact link)
  viewer/src/main/java/nl/b3p/viewer/stripes/ApplicationActionBean.java
Labels: :bomb: bug, Hacktoberfest :beers:

#1218 Bug/start map is wrong for workversion from app with mashup
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ApplicationSettingsActionBean.java
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ChooseApplicationActionBean.java
  viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/ChooseApplicationActionBeanTest.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/Application.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/ApplicationLayer.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/Level.java
  viewer-config-persistence/src/test/java/nl/b3p/viewer/config/app/ApplicationTest.java
Labels: :bomb: bug, Hacktoberfest :beers:, viewer-admin, viewer-config-persistence

#1222 Added A0 Printstylesheet
  viewer/src/main/webapp/WEB-INF/xsl/print/A0_Landscape.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A0_Portrait.xsl
Labels: Hacktoberfest :beers:, enhancement :+1:

#1223 Added A5 printstylesheets
  viewer/src/main/webapp/WEB-INF/xsl/print/A5_Landscape.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A5_Portrait.xsl
Labels: Hacktoberfest :beers:, enhancement :+1:

#1224 Allow to set application title (used as browser title)
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ApplicationSettingsActionBean.java
  viewer-admin/src/main/webapp/WEB-INF/jsp/application/applicationSettings.jsp
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/Application.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/databaseupdate/DatabaseSynchronizer.java
  viewer-config-persistence/src/main/resources/scripts/oracle-add_application_title.sql
  viewer-config-persistence/src/main/resources/scripts/postgresql-add_application_title.sql
  viewer-config-persistence/src/test/resources/nl/b3p/viewer/util/testdata.sql
  viewer/src/main/java/nl/b3p/viewer/stripes/ApplicationActionBean.java
  viewer/src/main/webapp/WEB-INF/jsp/app.jsp
  viewer/src/main/webapp/viewer-html/common/AppLoader.js
Labels: enhancement :+1:, viewer

#1227 if title is null or empty use application name
  viewer/src/main/java/nl/b3p/viewer/stripes/ApplicationActionBean.java
Labels: :bomb: bug, Hacktoberfest :beers:, viewer

#1229 Backport/start map is wrong for workversion from app with mashup
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ApplicationSettingsActionBean.java
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ChooseApplicationActionBean.java
  viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/ChooseApplicationActionBeanTest.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/Application.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/ApplicationLayer.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/Level.java
  viewer-config-persistence/src/test/java/nl/b3p/viewer/config/app/ApplicationTest.java
Labels: :bomb: bug

#1234 fix 'Application null not found' error using IE opening index.jsp
  viewer/src/main/webapp/index.jsp
Labels: :bomb: bug

#1237 Remap mothercomponent of mashup to component of new application
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ApplicationSettingsActionBean.java
  viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/ChooseApplicationActionBeanTest.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/Application.java
  viewer-config-persistence/src/test/java/nl/b3p/viewer/util/TestActionBeanContext.java
Labels: :bomb: bug

#1252 use https URLs for the b3p domain
  .travis.yml
  Jenkinsfile
  pom.xml
Labels: build infrastructure

#1253 use https URLs for the b3p domain
  .travis.yml
  Jenkinsfile
  pom.xml
Labels: Hacktoberfest :beers:, build infrastructure

#1251 Impr/load large wm ses
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/GeoServiceActionBean.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/ArcGISService.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/ArcIMSService.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/Layer.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/TileService.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/WMSService.java
Labels: enhancement :+1:
