Repository B3Partners/tailormap, pull requests merged in 2018-09, with the labels that each got.

#1201 Bugs/search in selectionmodule
  viewer/src/main/webapp/viewer-html/components/SelectionModule.js
Labels: :bomb: bug, viewer

#1202 Add help button, if configured, to all screen comp
  viewer/src/main/webapp/viewer-html/components/AttributeList.js
  viewer/src/main/webapp/viewer-html/components/Component.js
  viewer/src/main/webapp/viewer-html/components/Edit.js
  viewer/src/main/webapp/viewer-html/components/ExtendedEdit.js
  viewer/src/main/webapp/viewer-html/components/ExtendedFeatureInfo.js
  viewer/src/main/webapp/viewer-html/components/Legend.js
  viewer/src/main/webapp/viewer-html/components/Search.js
  viewer/src/main/webapp/viewer-html/components/SimpleFilter.js
  viewer/src/main/webapp/viewer-html/components/SpatialFilter.js
  viewer/src/main/webapp/viewer-html/components/TOC.js
  viewer/src/main/webapp/viewer-html/components/TransparencySlider.js
  viewer/src/main/webapp/viewer-html/components/components.json
Labels: enhancement :+1:, viewer

#1209 pass bookmark code when logging in
  viewer/src/main/java/nl/b3p/viewer/stripes/ApplicationActionBean.java
Labels: :bomb: bug

#1211 Check if menu exists. If not, don't hide it
  viewer/src/main/webapp/viewer-html/components/ExternalLinks.js
Labels: :bomb: bug

#1208 pass bookmark code when logging in
  viewer/src/main/java/nl/b3p/viewer/stripes/ApplicationActionBean.java
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
Labels: :bomb: bug
