Repository B3Partners/tailormap, pull requests merged in 2018-04, with the labels that each got.

#1019 Update Maven plugins and test dependencies
  pom.xml
  viewer-admin/pom.xml
  viewer/pom.xml
Labels: build infrastructure

#1021 Use flamingocql for translating cql strings to geotools Filters
  viewer/src/main/java/nl/b3p/viewer/stripes/ArcQueryUtilActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/BufferActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/DownloadFeaturesActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/FeatureExtentActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/FeatureInfoActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/FeatureReportActionBean.java
Labels: :bomb: bug

#1023 Fixes mantis issue 10289: mashup should honor rights of motherapplication
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ApplicationTreeLevelActionBean.java
Labels: :bomb: bug

#1024 Retrieve wmts capabilities with httpclient (use credentials). Added a…
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/GeoServiceActionBean.java
  viewer-admin/src/main/webapp/WEB-INF/jsp/services/geoservice.jsp
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/TileService.java
  viewer-config-persistence/src/test/java/nl/b3p/viewer/config/services/TileServiceTest.java
  viewer/src/main/java/nl/b3p/viewer/stripes/ProxyActionBean.java
Labels: enhancement :+1:, featurerequest :+1:
