Repository B3Partners/tailormap, pull requests merged in 2019-06, with the labels that each got.

#1469 Fix JS error when drawing
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/Utils.js
Labels: :bomb: bug

#1470 Create iterator object otherwise it will run forever
  viewer-audit/src/main/java/nl/b3p/viewer/audit/LoggingServiceFactory.java
Labels: :bomb: bug

#1473 Use correct cql parser
  viewer/src/main/java/nl/b3p/viewer/stripes/FeatureInfoActionBean.java
Labels: :bomb: bug, backport v5.4.x, viewer

#1475 Fix/attribute order extended feature info
  viewer/src/main/webapp/viewer-html/components/ExtendedFeatureInfo.js
  viewer/src/main/webapp/viewer-html/components/Maptip.js
Labels: :bomb: bug, backport v5.4.x

#1476 Imrp/remove unnecessary config extended feature info
  viewer/src/main/webapp/viewer-html/components/ExtendedFeatureInfo-config.js
  viewer/src/main/webapp/viewer-html/components/SelectionWindowConfig.js
Labels: enhancement :+1:

#1482 Add config id to each document to ensure uniqueness
  solr-commons/src/main/java/nl/b3p/viewer/solr/SolrUpdateJob.java
Labels: :bomb: bug, backport v5.4.x
