Repository B3Partners/tailormap, pull requests merged in 2019-10, with the labels that each got.

#1556 fix the bounds of pdok topo WMTS service
  viewer-config-persistence/src/test/java/nl/b3p/viewer/config/services/TileServiceTest.java
Labels: Hacktoberfest :beers:, backport v5.2.x, backport v5.4.x, build infrastructure

#1555 Use correct stringutils lib
  viewer-commons/src/main/java/nl/b3p/i18n/ResourceBundleToJsProvider.java
  viewer-config-persistence/src/test/java/nl/b3p/viewer/util/TestUtil.java
Labels: Hacktoberfest :beers:, dependencies

#1561 Fixes #1560 - check if ssosessionid is null before adding to the method
  viewer/src/main/java/nl/b3p/viewer/print/PrintUtil.java
Labels: :bomb: bug

#1562 WIP Bug/various edit tab fixes
  viewer-admin/src/main/webapp/resources/js/application/applicationTreeLayer.js
  viewer/src/main/java/nl/b3p/viewer/stripes/FileUploadActionBean.java
  viewer/src/main/webapp/viewer-html/components/Edit.js
  viewer/src/main/webapp/viewer-html/components/ExtendedEdit.js
Labels: :bomb: bug, featurerequest :+1:

#1291 Fixes for lgtm
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ApplicationTreeLayerActionBean.java
  viewer-commons/src/main/java/org/opensphere/geometry/triangulation/DoubleComparator.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/BoundingBox.java
  viewer/src/main/java/nl/b3p/viewer/image/CombineImageSettings.java
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersMapComponent.js
Labels: Hacktoberfest :beers:, enhancement :+1:, task

#1565 If Flamingo is running in iframe, iOS keeps firing resize events
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
Labels: :bomb: bug

#1567 codecov.io improvements
  Jenkinsfile
  appveyor.yml
  pom.xml
Labels: build infrastructure

#1550 Enable "typeAhead" on combo in Edit component
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: Hacktoberfest :beers:, enhancement :+1:, featurerequest :+1:

#1572 Put the restricting query in the fq field for solr, so it will not be…
  viewer/src/main/java/nl/b3p/viewer/search/SolrSearchClient.java
Labels: :bomb: bug, backport v5.2.x, backport v5.4.x, security

#1571 Bug/various edit tab fixes
  viewer/src/main/java/nl/b3p/viewer/stripes/EditFeatureActionBean.java
  viewer/src/main/webapp/viewer-html/components/Edit.js
  viewer/src/main/webapp/viewer-html/components/EditBulk.js
  viewer/src/main/webapp/viewer-html/components/ExtendedEdit.js
Labels: :bomb: bug

#1554 updated solr-core
  pom.xml
  viewer-admin/pom.xml
  viewer-audit/pom.xml
  viewer-commons/pom.xml
  viewer/pom.xml
Labels: Hacktoberfest :beers:, dependencies

#1524 Upgrade to GeoTools 22.x (and drop ArcIMS support)
  pom.xml
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/AttributeSourceActionBean.java
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/GeoServiceActionBean.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcgis/ArcGISDataStoreFactory.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcgis/FilterToArcGISSQL.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/ArcIMSDataStore.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/ArcIMSDataStoreFactory.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/ArcIMSFeatureReader.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/ArcIMSFeatureSource.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/ArcIMSServer.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/ArcXMLRequest.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/ArcXMLUtils.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/FilterToArcXMLSQL.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/ArcXML.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlBuffer.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlCoords.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlEnvelope.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlException.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlFClass.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlFeature.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlFeatureCount.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlFeatures.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlField.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlFieldInfo.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlGeometry.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlGetFeatures.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlGetServiceInfo.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlLayerInfo.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlMultiPoint.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlPolygon.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlPolyline.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlProperties.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlQuery.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlRequest.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlResponse.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlRing.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlServiceInfo.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlSpatialFilter.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcims/axl/AxlSpatialQuery.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/ArcIMSService.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/ArcXMLFeatureSource.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/Layer.java
  viewer-config-persistence/src/test/resources/nl/b3p/viewer/util/testdata.sql
  viewer/pom.xml
  viewer/src/main/java/nl/b3p/viewer/features/StreamingShapeWriter.java
  viewer/src/main/java/nl/b3p/viewer/stripes/ArcQueryUtilActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/MergeFeaturesActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/ServiceActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/SplitFeatureActionBean.java
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en.properties
  viewer/src/main/webapp/WEB-INF/jsp/app.jsp
  viewer/src/main/webapp/viewer-html/common/ajax/ArcQueryUtil.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/MapComponent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoArcIMSLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/flamingo/FlamingoMapComponent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersArcIMSLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersMapComponent.js
  viewer/src/main/webapp/viewer-html/minify.bat
Labels: GeoTools, Hacktoberfest :beers:, dependencies

#1386 Make OpenLayers 5 available
  viewer/pom.xml
  viewer/src/main/webapp/WEB-INF/jsp/app.jsp
  viewer/src/main/webapp/viewer-html/common/layout.js
  viewer/src/main/webapp/viewer-html/common/ol/debug/ol.js
  viewer/src/main/webapp/viewer-html/common/ol/debug/ol.js.map
  viewer/src/main/webapp/viewer-html/common/ol/ol.css
  viewer/src/main/webapp/viewer-html/common/ol/ol.js
  viewer/src/main/webapp/viewer-html/common/ol/proj4.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Map.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/OlArcLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/OlArcServerLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/OlComponent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/OlImageLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/OlLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/OlMapComponent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/OlSnappingController.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/OlTilingLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/OlTool.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/OlVectorLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/OlWMSLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/OpenLayers5Map.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/ToolMapClick.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/Utils.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/components/LoadingPanel.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/components/OlLoadMonitor.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/components/OlMaptip.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/components/OlOverview.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/components/panZoomBar.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/tools/DragPan.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/tools/FullExtent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/tools/Measure.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/tools/NextExtent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/tools/OlDefaultTool.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/tools/OlIdentifyTool.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/tools/PrevExtent.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/tools/StreetViewButton.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/tools/ToolButton.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/tools/ZoomIn.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/tools/ZoomOutButton.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersMapComponent.js
  viewer/src/main/webapp/viewer-html/components/Coordinates.js
  viewer/src/main/webapp/viewer-html/components/Legend.js
  viewer/src/main/webapp/viewer-html/components/Maptip.js
  viewer/src/main/webapp/viewer-html/components/components.json
  viewer/src/main/webapp/viewer-html/components/tools/Measure.js
Labels: enhancement :+1:

#1575 typo
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
Labels: backport v5.6.x

#1582 [Backport v5.2.x] Bump quartz from 2.3.1 to 2.3.2
  pom.xml
Labels: dependencies, security

#1585 remove the ArcIMSDataStoreFactory from the services file
  viewer-commons/src/main/resources/META-INF/services/org.geotools.data.DataStoreFactorySpi
Labels: :bomb: bug, backport v5.6.x

#1587 Fixed typo, so wmslayers without legendgraphicurl will not give an er…
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/WMSLayer.js
Labels: :bomb: bug, backport v5.4.x, backport v5.6.x
