Repository B3Partners/tailormap, pull requests merged in 2019-03, with the labels that each got.

#1368 Fixed #1316: overridden some OL2 functions. Problem seemed to be some…
  viewer/src/main/webapp/viewer-html/common/openlayers/lib/OpenLayers/Layer/Vector.js
  viewer/src/main/webapp/viewer-html/common/openlayers/lib/OpenLayers/Renderer/SVG.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/Utils.js
Labels: :bomb: bug

#1373 try to fix the travis file
  .travis.yml
  pom.xml
  viewer-commons/pom.xml
Labels: build infrastructure

#1375 Fixed #1316: overridden some OL2 functions. Problem seemed to be some…
  viewer/src/main/webapp/viewer-html/common/openlayers/lib/OpenLayers/Layer/Vector.js
  viewer/src/main/webapp/viewer-html/common/openlayers/lib/OpenLayers/Renderer/SVG.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/Utils.js
Labels: :bomb: bug

#1377 Bug/split merge line strings
  viewer/src/main/java/nl/b3p/viewer/stripes/SplitFeatureActionBean.java
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersSnappingController.js
Labels: :bomb: bug, enhancement :+1:

#1383 use Apache Tika to detect png mimetype in TilingIntegrationTest
  pom.xml
  viewer/pom.xml
  viewer/src/test/java/nl/b3p/viewer/image/TilingIntegrationTest.java
Labels: build infrastructure, enhancement :+1:

#1382 reenable createVertices, but switch it off when dummyUser mode is use…
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersVectorLayer.js
  viewer/src/main/webapp/viewer-html/components/Drawing.js
Labels: :bomb: bug

#1384 Feat/reduce app config
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/LayoutManagerActionBean.java
  viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/GeoServiceActionBeanTest.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/Application.java
  viewer/src/main/java/nl/b3p/viewer/stripes/ApplicationActionBean.java
Labels: enhancement :+1:

#1389 Bump GeoTools 20.2 -> 20.3
  pom.xml
Labels: dependencies

#1390 [5.4.x] Bump GeoTools 20.2 -> 20.3
  pom.xml
  viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/GeoServiceActionBeanTest.java
Labels: dependencies

#1394 Prevent solr server init when no url configured
  solr-commons/pom.xml
  solr-commons/src/main/java/nl/b3p/viewer/solr/SolrInitializer.java
Labels: enhancement :+1:, solr-commons

#1396 Bump quartz from 2.3.0 to 2.3.1
  pom.xml
Labels: dependencies

#1398 Remove level from level.children which are not the new parent
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ApplicationTreeActionBean.java
Labels: :bomb: bug

#1397 Remove level from level.children which are not the new parent
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ApplicationTreeActionBean.java
Labels: :bomb: bug

#1399 Backport fixes
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en_US.properties
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en_US.properties
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/components/OpenLayersBorderNavigation.js
  viewer/src/main/webapp/viewer-html/components/Bookmark-config.js
  viewer/src/main/webapp/viewer-html/components/Bookmark.js
  viewer/src/main/webapp/viewer-html/components/Contactform-config.js
  viewer/src/main/webapp/viewer-html/components/Drawing.js
  viewer/src/main/webapp/viewer-html/components/ExtendedEdit.js
  viewer/src/main/webapp/viewer-html/components/Legend.js
  viewer/src/main/webapp/viewer-html/components/Maptip.js
  viewer/src/main/webapp/viewer-html/components/Print.js
  viewer/src/main/webapp/viewer-html/components/Search-config.js
  viewer/src/main/webapp/viewer-html/components/Search.js
  viewer/src/main/webapp/viewer-html/components/resources/css/maptip.css
  viewer/src/main/webapp/viewer-html/components/tools/Zoom.js
  viewer/src/main/webapp/viewer-html/svg/svgsprite.css
Labels: :bomb: bug

#1387 Fix/540 rc fixes
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en_US.properties
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en_US.properties
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/components/OpenLayersBorderNavigation.js
  viewer/src/main/webapp/viewer-html/components/Bookmark-config.js
  viewer/src/main/webapp/viewer-html/components/Bookmark.js
  viewer/src/main/webapp/viewer-html/components/Contactform-config.js
  viewer/src/main/webapp/viewer-html/components/Drawing.js
  viewer/src/main/webapp/viewer-html/components/ExtendedEdit.js
  viewer/src/main/webapp/viewer-html/components/Legend.js
  viewer/src/main/webapp/viewer-html/components/Maptip.js
  viewer/src/main/webapp/viewer-html/components/Print.js
  viewer/src/main/webapp/viewer-html/components/Search-config.js
  viewer/src/main/webapp/viewer-html/components/Search.js
  viewer/src/main/webapp/viewer-html/components/resources/css/maptip.css
  viewer/src/main/webapp/viewer-html/components/tools/Zoom.js
  viewer/src/main/webapp/viewer-html/svg/svgsprite.css
Labels: :bomb: bug, enhancement :+1:, viewer

#1388 Fixes issue with overlapping resize handles
  viewer/src/main/webapp/resources/css/viewer.css
Labels: :bomb: bug, viewer

#1393 Backport/reduce app config
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/LayoutManagerActionBean.java
  viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/GeoServiceActionBeanTest.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/Application.java
  viewer/src/main/java/nl/b3p/viewer/stripes/ApplicationActionBean.java
Labels: enhancement :+1:

#1402 reset mode after layerchanged; in the superclass mode is set to null …
  viewer/src/main/webapp/viewer-html/components/ExtendedEdit.js
Labels: :bomb: bug
