Repository B3Partners/tailormap, pull requests merged in 2019-05, with the labels that each got.

#1426 Check if applayer is present: can be undefined when using authorizati…
  viewer/src/main/webapp/viewer-html/components/SimpleFilter.js
Labels: :bomb: bug

#1422 Small fixes after PR #1401
  viewer/src/main/webapp/viewer-html/components/Edit.js
  viewer/src/main/webapp/viewer-html/components/SelectionWindowConfig.js
Labels: :bomb: bug

#1379 Use streetsmart api 19.3
  viewer/src/main/webapp/cyclomedia.html
  viewer/src/main/webapp/resources/js/b3p-cyclomedia-wrapper.js
Labels: enhancement :+1:

#1432 [backport] Restore ontbranding to master
  viewer/src/main/java/nl/b3p/viewer/stripes/OntbrandingsActionBean.java
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en_US.properties
  viewer/src/main/webapp/viewer-html/components/Ontbrandingsaanvraag.js
Labels: :bomb: bug

#1431 Restore ontbranding
  viewer/src/main/java/nl/b3p/viewer/stripes/OntbrandingsActionBean.java
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en_US.properties
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Feature.js
  viewer/src/main/webapp/viewer-html/components/Ontbrandingsaanvraag.js
Labels: :bomb: bug

#1429 Highlighting geometries and showing multiple styles in TOC
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ApplicationTreeLayerActionBean.java
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en_US.properties
  viewer-admin/src/main/webapp/WEB-INF/jsp/application/applicationTreeLayer.jsp
  viewer-admin/src/main/webapp/resources/js/application/applicationTreeLayer.js
  viewer-admin/src/main/webapp/resources/js/application/layer/stylestree.js
  viewer/src/main/java/nl/b3p/viewer/search/AttributeSourceSearchClient.java
  viewer/src/main/java/nl/b3p/viewer/search/SolrSearchClient.java
  viewer/src/main/java/nl/b3p/viewer/stripes/SimplifyFeatureActionBean.java
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en_US.properties
  viewer/src/main/webapp/WEB-INF/jsp/app.jsp
  viewer/src/main/webapp/resources/css/viewer.css
  viewer/src/main/webapp/resources/images/extjs-overrides/touch-crisp/radio.png
  viewer/src/main/webapp/resources/images/wand.png
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Event.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/WMSLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersVectorLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersWMSLayer.js
  viewer/src/main/webapp/viewer-html/components/AttributeList.js
  viewer/src/main/webapp/viewer-html/components/Highlight-config.js
  viewer/src/main/webapp/viewer-html/components/Highlight.js
  viewer/src/main/webapp/viewer-html/components/Legend.js
  viewer/src/main/webapp/viewer-html/components/Maptip.js
  viewer/src/main/webapp/viewer-html/components/Search.js
  viewer/src/main/webapp/viewer-html/components/TOC.js
  viewer/src/main/webapp/viewer-html/components/components.json
Labels: featurerequest :+1:, viewer

#1434 Check if styles are configured
  viewer-admin/src/main/webapp/WEB-INF/jsp/application/applicationTreeLayer.jsp
  viewer/src/main/webapp/viewer-html/components/TOC.js
Labels: :bomb: bug

#1435 Added function for highlighting active features in extendedfeatureinfo
  viewer/src/main/java/nl/b3p/viewer/stripes/SimplifyFeatureActionBean.java
  viewer/src/main/webapp/viewer-html/components/ExtendedFeatureInfo.js
Labels: enhancement :+1:

#1430 Renamed as per @matthijsln suggestion
  viewer-admin/src/main/resources/ViewerResources_en.properties
  viewer-admin/src/main/webapp/WEB-INF/web.xml
  viewer/src/main/resources/ViewerResources_en.properties
  viewer/src/main/webapp/WEB-INF/web.xml
Labels: :bomb: bug

#1367 Java 11 support
  .travis.yml
  Jenkinsfile
  appveyor.yml
  pom.xml
  solr-commons/src/main/java/nl/b3p/viewer/solr/SolrUpdateJob.java
  tomcat-lib/README.md
  tomcat-lib/assembly.xml
  tomcat-lib/pom.xml
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/CycloramaConfigurationActionBean.java
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/GeoServiceActionBean.java
  viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/GeoServiceActionBeanTest.java
  viewer-commons/pom.xml
  viewer-config-persistence/pom.xml
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/BoundingBox.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/Layer.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/WMSService.java
  viewer/pom.xml
  viewer/src/main/java/nl/b3p/viewer/image/ImageTool.java
  viewer/src/main/java/nl/b3p/viewer/stripes/AttributesActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/CycloramaActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/DownloadFeaturesActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/MergeFeaturesActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/SldActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/SplitFeatureActionBean.java
  viewer/src/main/java/nl/b3p/viewer/util/FeatureToJson.java
  viewer/src/test/java/nl/b3p/viewer/image/TilingIntegrationTest.java
  web-commons/pom.xml
  web-commons/src/main/java/nl/b3p/web/stripes/StripersistCleanupListener.java
Labels: GeoTools, build infrastructure, dependencies, enhancement :+1:, java 9+

#1443 update Jenkinsfile and property files for oracle connection
  .jenkins/insert-fla-version.sh
  Jenkinsfile
  viewer-admin/src/test/resources/oracle.properties
  viewer/src/test/resources/oracle.properties
Labels: build infrastructure, task

#1444 update Jenkinsfile and property files for oracle connection [5.4.x]
  .jenkins/insert-fla-version.sh
  Jenkinsfile
  viewer-admin/src/test/resources/oracle.properties
  viewer/src/test/resources/oracle.properties
Labels: build infrastructure

#1450 Add a `geometry_columns` key to the datastore params
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/JDBCFeatureSource.java
Labels: enhancement :+1:, viewer

#1451 don't set currentSearchID when there are more searchconfigs than 1 [v5.2.x]
  viewer/src/main/webapp/viewer-html/components/Search.js
Labels: :bomb: bug

#1452 don't set currentSearchID when there are more searchconfigs than 1
  viewer/src/main/webapp/viewer-html/components/Search.js
Labels: :bomb: bug

#1455 Fixes dragging vertices after splitting [5.4.x]
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersMap.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/Utils.js
  viewer/src/main/webapp/viewer-html/components/Drawing.js
  viewer/src/main/webapp/viewer-html/components/Split.js
Labels: :bomb: bug

#1449 Agelfixes
  viewer-admin/src/main/webapp/resources/js/application/layer/stylestree.js
  viewer/src/main/webapp/viewer-html/components/Maptip.js
  viewer/src/main/webapp/viewer-html/components/TOC.js
Labels: :bomb: bug, enhancement :+1:

#1440 add serviceId to legendpart when creating legendgraphic
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/WMSLayer.js
Labels: :bomb: bug

#1454 Fixes dragging vertices after splitting
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersMap.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/Utils.js
  viewer/src/main/webapp/viewer-html/components/Drawing.js
  viewer/src/main/webapp/viewer-html/components/Split.js
Labels: :bomb: bug

#1457 Use actionBeans['proxy'] global to set OpenLayers.ProxyHost
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/SelectedContentCache.java
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/tools/OpenLayersIdentifyTool.js
Labels: :bomb: bug

#1459 Feat/1453 allow draw circle in edit
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en.properties
  viewer/src/main/webapp/resources/css/viewer.css
  viewer/src/main/webapp/viewer-html/components/Component.js
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: enhancement :+1:, viewer

#1441 Bug/wmts printing
  viewer/src/main/java/nl/b3p/viewer/image/CombineWMTSUrl.java
  viewer/src/main/java/nl/b3p/viewer/image/ImageCollector.java
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersTilingLayer.js
Labels: :bomb: bug

#1442 Backport/bug/wmts printing
  viewer/src/main/java/nl/b3p/viewer/image/CombineWMTSUrl.java
  viewer/src/main/java/nl/b3p/viewer/image/ImageCollector.java
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersTilingLayer.js
Labels: :bomb: bug

#1461 delete java 11 artifacts from local Jenkins repostory after testing
  Jenkinsfile
  pom.xml
Labels: build infrastructure

#1462 Bump tika-core 1.20 -> 1.21
  pom.xml
Labels: dependencies

#1467 update GH community files, create security policy
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  .github/SECURITY.md
  .github/repository-open-graph-FlamingoLogo.png
  README.md
Labels: task
