Repository B3Partners/tailormap, pull requests merged in 2019-09, with the labels that each got.

#1527 fix trailing komma and other code-style issues in edit.js
  viewer/pom.xml
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: :bomb: bug, build infrastructure, viewer

#1534 Remove incorrect check
  viewer/src/main/webapp/viewer-html/components/Legend.js
Labels: :bomb: bug, backport v5.4.x

#1530 [BACKPORT 5.4.x] Fixes using the selectionmodule after searching (and adding a layer t…
  viewer/src/main/webapp/viewer-html/components/Search.js
Labels: :bomb: bug

#1537 use "Maven CURRENT" on the Jenkins service
  Jenkinsfile
Labels: backport v5.4.x, build infrastructure

#1538 [BACKPORT 5.4.x] use "Maven CURRENT" on the Jenkins service
  Jenkinsfile
Labels: build infrastructure

#1532 Load features from bookmark in drawing after all layers are initialized.
  viewer/src/main/webapp/viewer-html/components/Drawing.js
Labels: :bomb: bug

#1536 Coordinate search functionality
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en.properties
  viewer/src/main/webapp/viewer-html/components/Search-config.js
  viewer/src/main/webapp/viewer-html/components/Search.js
Labels: featurerequest :+1:

#1533 Logging and printing improvements
  viewer/src/main/java/nl/b3p/viewer/image/CombineImagesHandler.java
  viewer/src/main/java/nl/b3p/viewer/image/ImageCollector.java
  viewer/src/main/java/nl/b3p/viewer/image/ImageManager.java
  viewer/src/main/java/nl/b3p/viewer/print/PrintUtil.java
  viewer/src/main/java/nl/b3p/viewer/stripes/CombineImageActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/PrintActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/ProxyActionBean.java
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en.properties
  viewer/src/main/webapp/authinfo.jsp
  viewer/src/test/java/nl/b3p/viewer/image/TilingIntegrationTest.java
  viewer/src/test/java/nl/b3p/viewer/image/WMSTest.java
  web-commons/src/main/java/nl/b3p/web/stripes/AuditLoggingInterceptor.java
Labels: enhancement :+1:

#1542 Initialize Auditmessage object upon making ProxyActionBean object
  viewer-config-persistence/src/test/java/nl/b3p/viewer/config/services/TileServiceTest.java
  viewer/src/main/java/nl/b3p/viewer/print/PrintInfo.java
Labels: :bomb: bug

#1543 Use 'flamingo.version' and not 'project.version' for any flamingo dependencies
  pom.xml
Labels: build infrastructure
