Repository B3Partners/tailormap, pull requests merged in 2019-02, with the labels that each got.

#1353 load pki-overheid G2/G3 certificates
  .travis.yml
  appveyor.yml
Labels: build infrastructure

#1354 Enhanced timeout for retrieval of appconfig. getString and optString …
  viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/WFSTypeNamingTest.java
  viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/WMSGeoServiceABTest.java
  viewer/src/main/java/nl/b3p/viewer/stripes/EditFeatureActionBean.java
  viewer/src/main/webapp/viewer-html/common/AppLoader.js
  viewer/src/test/java/nl/b3p/viewer/stripes/AttributesActionBeanTest.java
  viewer/src/test/java/nl/b3p/viewer/util/FeatureToJsonTest.java
  viewer/src/test/java/nl/b3p/viewer/util/FlamingoCQLTest.java
Labels: :bomb: bug

#1356 Feat/mob fixes
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/ApplicationLayer.java
  viewer/src/main/java/nl/b3p/viewer/stripes/EditFeatureActionBean.java
  viewer/src/main/webapp/WEB-INF/web.xml
  viewer/src/main/webapp/viewer-html/common/AppLoader.js
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: enhancement :+1:

#1357 Fixes for snapping button in edit component: user can now disable sna…
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: :bomb: bug, enhancement :+1:

#1360 Don't clean away the test and integration-test results
  .travis.yml
  Jenkinsfile
  appveyor.yml
Labels: build infrastructure

#1361 attempt to fix some integration tests for windows
  viewer-admin/pom.xml
  viewer-admin/src/test/java/nl/b3p/viewer/admin/ViewerAdminLockoutIntegrationTest.java
  viewer/pom.xml
  viewer/src/test/java/nl/b3p/viewer/image/TilingIntegrationTest.java
  viewer/src/test/java/nl/b3p/viewer/image/WMS.java
Labels: build infrastructure

#1343 Support for MS SQL Server 2017 as a configuration backend
  appveyor.yml
  pom.xml
  viewer-admin/pom.xml
  viewer-admin/src/main/webapp/META-INF/context.xml
  viewer-admin/src/test/java/nl/b3p/viewer/admin/ViewerAdminLockoutIntegrationTest.java
  viewer-admin/src/test/resources/ms_sql_server.properties
  viewer-admin/src/test/tomcatconf/appveyorcontext.xml
  viewer-config-persistence/pom.xml
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/stripersist/DynamicStripersistInitializer.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/databaseupdate/DatabaseSynchronizer.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/databaseupdate/ScriptRunner.java
  viewer-config-persistence/src/main/resources/META-INF/orm-microsoft_sql_server.xml
  viewer-config-persistence/src/main/resources/META-INF/persistence.xml
  viewer-config-persistence/src/main/resources/scripts/hqsqldb-initialize_categories.sql
  viewer-config-persistence/src/main/resources/scripts/initialize_database.sql
  viewer-config-persistence/src/main/resources/scripts/microsoft_sql_server-initialize_categories.sql
  viewer-config-persistence/src/main/resources/scripts/oracle-initialize_categories.sql
  viewer-config-persistence/src/main/resources/scripts/postgresql-initialize_categories.sql
  viewer/pom.xml
  viewer/src/main/webapp/META-INF/context.xml
  viewer/src/main/webapp/WEB-INF/classes/log4j.properties
  viewer/src/test/java/nl/b3p/viewer/image/TilingIntegrationTest.java
  viewer/src/test/java/nl/b3p/viewer/image/WMS.java
  viewer/src/test/resources/ms_sql_server.properties
  viewer/src/test/tomcatconf/appveyorcontext.xml
Labels: featurerequest :+1:

#1362 Add MS SQL Server 2017 as an attribute source
  pom.xml
  viewer-admin/src/main/webapp/WEB-INF/jsp/services/editattributesource.jsp
  viewer-config-persistence/pom.xml
Labels: GeoTools, enhancement :+1:, viewer-admin, viewer-config-persistence
