Repository B3Partners/tailormap, pull requests merged in 2019-08, with the labels that each got.

#1506 Allow for setting alignment options in Coordinates component
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en.properties
  viewer/src/main/webapp/viewer-html/common/resources/css/openlayers.css
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersMapComponent.js
  viewer/src/main/webapp/viewer-html/components/Coordinates-config.js
  viewer/src/main/webapp/viewer-html/components/Coordinates.js
  viewer/src/main/webapp/viewer-html/components/components.json
Labels: enhancement :+1:

#1500 Prevent having more than one GeoTools EPSG authority
  pom.xml
  viewer/src/test/java/nl/b3p/viewer/MultipleEPSGAuthoritiesIntegrationTest.java
  viewer/src/test/java/nl/b3p/viewer/MultipleGeoToolsVersionsInWarIntegrationTest.java
Labels: :bomb: bug, viewer

#1502 Update OWASP dependency scanner configuration
  .mvn/owasp-hints.xml
  .mvn/owasp-suppression.xml
  Jenkinsfile
  pom.xml
Labels: backport v5.2.x, backport v5.4.x, build infrastructure, security

#1509 Bump Apache tika and MS SQL jdbc driver to latest release
  pom.xml
Labels: dependencies

#1513 [Backport v5.4.x] Bump mssql-jdbc from 7.2.2.jre8 to 7.4.1.jre8
  pom.xml
Labels: dependencies

#1515 Bump commons-beanutils-core 1.8.3 to commons-beanutils 1.9.3
  pom.xml
  viewer-config-persistence/pom.xml
Labels: backport v5.4.x, dependencies, security

#1523 add mutliple recipients/cc with comma separated string
  viewer-commons/src/main/java/nl/b3p/mail/Mailer.java
Labels: enhancement :+1:

#1504 Feat/automatic date and user field
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ApplicationTreeLayerActionBean.java
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en.properties
  viewer-admin/src/main/webapp/resources/js/application/applicationTreeLayer.js
  viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/ApplicationTreeLayerActionBeanTest.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/ConfiguredAttribute.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/databaseupdate/DatabaseSynchronizer.java
  viewer-config-persistence/src/main/resources/scripts/microsoft_sql_server-automatic_attributes.sql
  viewer-config-persistence/src/main/resources/scripts/oracle-automatic_attributes.sql
  viewer-config-persistence/src/main/resources/scripts/postgresql-automatic_attributes.sql
  viewer-config-persistence/src/test/resources/nl/b3p/viewer/util/testdata.sql
  viewer/src/main/java/nl/b3p/viewer/stripes/EditFeatureActionBean.java
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: featurerequest :+1:
