Repository B3Partners/tailormap, pull requests merged in 2019-12, with the labels that each got.

#1618 [Backport v5.6.x] Bump mockito-core from 3.1.0 to 3.2.0
  pom.xml
Labels: backport v5.4.x, build infrastructure, dependencies

#1623 Bug/featuretypes dont get deleted on feature source update
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/UpdatableFeatureSource.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/databaseupdate/DatabaseSynchronizer.java
  viewer-config-persistence/src/main/resources/scripts/delete_orphan_featuretypes.sql
  viewer-config-persistence/src/test/resources/nl/b3p/viewer/util/testdata.sql
Labels: :bomb: bug, viewer-admin

#1629 Travis-CI - migrate from .org to .com
  README.md
  pom.xml
Labels: backport v5.4.x, backport v5.6.x, build infrastructure

#1632 [security] Bump tomcat deps to 7.0.99 to fix CVE-2019-17563 and CVE-2019-12418
  pom.xml
Labels: backport v5.4.x, backport v5.6.x, build infrastructure, security

#1634 [Backport v5.4.x] [security] Bump tomcat deps to 7.0.99 to fix CVE-2019-17563 and CVE-2019-12418
  pom.xml
Labels: build infrastructure, security

#1637 [Backport v5.6.x] use returnTo from URL param after successful login for direct mellon …
  web-commons/src/main/java/nl/b3p/web/filter/HeaderAuthenticationFilter.java
Labels: :bomb: bug

#1636 [Backport v5.4.x] use returnTo from URL param after successful login for direct mellon …
  web-commons/src/main/java/nl/b3p/web/filter/HeaderAuthenticationFilter.java
Labels: :bomb: bug

#1638 Create a Mac OS Maven action
  .github/workflows/macos-maven.yml
Labels: backport v5.4.x, backport v5.6.x, build infrastructure
