Repository B3Partners/tailormap, pull requests merged in 2019-01, with the labels that each got.

#1310 Bump GeoTools 19.3 to 19.4
  pom.xml
Labels: GeoTools, dependencies

#1271 Adds A1 and A2 printing
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en_US.properties
  viewer/src/main/java/nl/b3p/viewer/stripes/PrintActionBean.java
  viewer/src/main/webapp/viewer-html/components/Print-config.js
  viewer/src/main/webapp/viewer-html/components/Print.js
Labels: featurerequest :+1:, viewer

#858 Better test coverage reporting
  .travis.yml
  Jenkinsfile
  pom.xml
  viewer-admin/pom.xml
  viewer-config-persistence/pom.xml
  viewer/pom.xml
Labels: build infrastructure, java 9+

#1329 legend header only shows when legend is available
  viewer/src/main/webapp/WEB-INF/xsl/print/A0_Landscape.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A0_Portrait.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A1_Landscape.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A1_Portrait.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A2_Landscape.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A2_Portrait.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A3_Landscape.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A3_Portrait.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A4_Landscape.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A4_Portrait.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A5_Landscape.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/A5_Portrait.xsl
  viewer/src/main/webapp/WEB-INF/xsl/print/legend.xsl
Labels: enhancement :+1:

#1328 add a null check for serviceLayer
  viewer/src/main/webapp/viewer-html/components/LayerContext.js
Labels: :bomb: bug

#1335 Bump GeoTools from 20.1 to 20.2
  pom.xml
Labels: dependencies

#1347 Change flamingo4.b3p.nl to flamingo5.b3p.nl
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ServiceUsageMatrixActionBean.java
  viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/WFSTypeNamingTest.java
  viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/WMSGeoServiceABTest.java
  viewer-config-persistence/src/test/java/nl/b3p/viewer/util/TestUtil.java
  viewer-config-persistence/src/test/resources/nl/b3p/viewer/util/testdata.sql
  viewer/src/test/java/nl/b3p/viewer/stripes/AttributesActionBeanTest.java
  viewer/src/test/java/nl/b3p/viewer/stripes/GeoToolsWfsTest.java
  viewer/src/test/java/nl/b3p/viewer/stripes/ProxyActionBeanTest.java
  viewer/src/test/java/nl/b3p/viewer/util/FeatureToJsonTest.java
Labels: build infrastructure

#1348 change flamingo4.b3p.nl to flamingo5.b3p.nl
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ServiceUsageMatrixActionBean.java
  viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/WFSTypeNamingTest.java
  viewer-admin/src/test/java/nl/b3p/viewer/admin/stripes/WMSGeoServiceABTest.java
  viewer-config-persistence/src/test/java/nl/b3p/viewer/util/TestUtil.java
  viewer-config-persistence/src/test/resources/nl/b3p/viewer/util/testdata.sql
  viewer/src/test/java/nl/b3p/viewer/stripes/AttributesActionBeanTest.java
  viewer/src/test/java/nl/b3p/viewer/stripes/ProxyActionBeanTest.java
  viewer/src/test/java/nl/b3p/viewer/util/FeatureToJsonTest.java
Labels: build infrastructure
