Repository B3Partners/tailormap, pull requests merged in 2019-07, with the labels that each got.

#1488 Bump dependency-check-maven from 4.0.2 to 5.1.0
  pom.xml
Labels: build infrastructure

#1489 fix getLayerLegendInfo call in FeatureReport
  viewer/src/main/webapp/viewer-html/components/FeatureReport.js
Labels: :bomb: bug, backport v5.4.x, viewer

#1485 Bump GeoTools 21.1 -> 21.2
  pom.xml
Labels: dependencies

#1490 Use V3, and add admin configured filters to the fq (filterqueries) pa…
  viewer/src/main/java/nl/b3p/viewer/search/PDOKSearchClient.java
Labels: enhancement :+1:, viewer

#1495 Bump com.oracle.jdbc:ojdbc8_g from 18.3.0.0 to 19.3.0.0
  pom.xml
Labels: build infrastructure, dependencies

#1492 Java 11 should build Java 8 compatible binaries
  pom.xml
Labels: build infrastructure, java 8, java 9+

#1497 Bump postgresql and sqlserver jdbc drivers
  pom.xml
Labels: dependencies, security

#1498 Add an integration test to check for multiple versions of GeoTools in the viewer war
  viewer/pom.xml
  viewer/src/test/java/nl/b3p/viewer/MultipleGeoToolsVersionsInWarIntegrationTest.java
Labels: build infrastructure

#1493 Delete package-lock.json
  .gitignore
  viewer/src/main/webapp/viewer-html/package-lock.json
Labels: build infrastructure, security

#1501 Method access changes in DownloadFeaturesActionBean and AttributesActionBean
  pom.xml
  viewer/src/main/java/nl/b3p/viewer/stripes/AttributesActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/DownloadFeaturesActionBean.java
Labels: featurerequest :+1:, viewer
