Repository B3Partners/tailormap, pull requests merged in 2019-11, with the labels that each got.

#1589 ArcIMS removal leftovers
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ServiceUsageMatrixActionBean.java
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en.properties
  viewer-admin/src/main/webapp/WEB-INF/jsp/services/editattributesource.jsp
  viewer-admin/src/main/webapp/WEB-INF/jsp/services/geoservice.jsp
  viewer-admin/src/main/webapp/resources/html/help.html
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcgis/FilterToArcGISSQL.java
  viewer/src/main/java/nl/b3p/viewer/image/ArcImsImageCollector.java
  viewer/src/main/java/nl/b3p/viewer/image/CombineArcIMSUrl.java
  viewer/src/main/java/nl/b3p/viewer/image/CombineImageSettings.java
  viewer/src/main/java/nl/b3p/viewer/image/ImageManager.java
  viewer/src/main/java/nl/b3p/viewer/stripes/ArcQueryUtilActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/CombineImageActionBean.java
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en.properties
  viewer/src/main/webapp/viewer-html/common/ajax/CSWClient.js
  viewer/src/main/webapp/viewer-html/common/ajax/ServiceInfo.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/ArcLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Layer.js
  viewer/src/main/webapp/viewer-html/components/SelectionModule.js
Labels: :bomb: bug, backport v5.6.x

#1592 update Maven plugins to current versions
  .travis.yml
  pom.xml
Labels: backport v5.6.x, build infrastructure

#1602 [Backport 5.4.x] Bump dependency-check-maven from 5.2.2 to 5.2.4
  pom.xml
Labels: build infrastructure

#1612 [Backport v5.6.x] update git-commit-id-plugin and maven-enforcer-plugin
  pom.xml
Labels: build infrastructure

#1613 [Backport v5.4.x] update git-commit-id-plugin and maven-enforcer-plugin
  pom.xml
Labels: build infrastructure

#1605 Bump geotools 20.3 -> 20.5
  pom.xml
Labels: build infrastructure, dependencies

#1604 Bump geotools 22.0 -> 22.1
  pom.xml
Labels: backport v5.6.x, dependencies

#1614 [Backport v5.6.x] Bump geotools 22.0 -> 22.1
  pom.xml
Labels: dependencies

#1615 added success message upon deleting feature; msg was undefined
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: :bomb: bug, backport v5.4.x, backport v5.6.x, viewer

#1616 [Backport v5.6.x] added success message upon deleting feature; msg was undefined
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: :bomb: bug
