Repository B3Partners/tailormap, pull requests merged in 2020-03, with the labels that each got.

#1718 Relocate Oracle driver com.oracle.jdbc ➜ com.oracle.database.jdbc
  pom.xml
  tomcat-lib/README.md
  tomcat-lib/pom.xml
  viewer-admin/pom.xml
  viewer/pom.xml
Labels: backport v5.6.x, dependencies

#1723 Feat/added expire date for user
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en.properties
  viewer-admin/src/main/webapp/WEB-INF/jsp/security/edituser.jsp
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/security/Authorizations.java
  viewer/src/main/java/nl/b3p/viewer/stripes/ApplicationActionBean.java
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en.properties
Labels: backport v5.6.x, enhancement :+1:, viewer-admin

#1727 [Backport v5.4.x] Bump apache.httpcomponents.version from 4.5.10 to 4.5.12
  pom.xml
Labels: dependencies

#1728 Fixed NPE
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/security/Authorizations.java
Labels: :bomb: bug

#1740 [Backport v5.4.x] Bump maven-site-plugin from 3.8.2 to 3.9.0
  pom.xml
Labels: build infrastructure

#1748 [Backport v5.4.x] Bump grunt from 1.0.4 to 1.1.0 in /viewer/src/main/webapp/viewer-html…
  viewer/src/main/webapp/viewer-html/package.json
Labels: build infrastructure

#1751 [Backport v5.4.x] Bump mockito-core from 3.3.1 to 3.3.3
  pom.xml
Labels: build infrastructure, dependencies

#1753 [Backport v5.4.x] Bump maven-javadoc-plugin from 3.1.1 to 3.2.0
  pom.xml
Labels: build infrastructure

#1749 [Backport v5.6.x] Bump grunt from 1.0.4 to 1.1.0 in /viewer/src/main/webapp/viewer-html
  viewer/src/main/webapp/viewer-html/package.json
Labels: build infrastructure

#1754 isAlternative = true from appLayer legends
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
Labels: :bomb: bug, backport v5.4.x, backport v5.6.x

#1759 [Backport v5.4.x] Bump javassist from 3.26.0-GA to 3.27.0-GA (#1757)
  pom.xml
Labels: dependencies

#1761 Fixes issue with Simple Filter layout
  viewer/src/main/webapp/viewer-html/components/SimpleFilter.js
  viewer/src/main/webapp/viewer-html/components/SimpleFilterFilters.js
Labels: :bomb: bug, backport v5.4.x, backport v5.6.x

#1766 Removed console.log
  viewer/src/main/webapp/viewer-html/components/SimpleFilter.js
Labels: :bomb: bug, backport v5.4.x, backport v5.6.x

#1773 bump dependencies & plugins
  .gitignore
  pom.xml
  viewer-admin/pom.xml
  viewer/pom.xml
Labels: backport v5.4.x, backport v5.6.x, build infrastructure, dependencies

#1775 [Backport 5.4.x] bump dependencies & plugins
  pom.xml
Labels: build infrastructure, dependencies
