Repository B3Partners/tailormap, pull requests merged in 2020-10, with the labels that each got.

#2032 Also load "Staat der Nederlanden EV Root CA" certificate on AppVeyor
  appveyor.yml
Labels: backport v5.4.x, backport v5.6.x, build infrastructure, hacktoberfest :beers:

#2031 Backport/performance layerlist
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/ApplicationLayer.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/databaseupdate/DatabaseSynchronizer.java
  viewer-config-persistence/src/test/resources/nl/b3p/viewer/util/testdata.sql
  viewer/src/main/webapp/viewer-html/common/ajax/LayerSelector.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
  viewer/src/main/webapp/viewer-html/components/FeatureReport.js
  viewer/src/main/webapp/viewer-html/components/Print.js
  viewer/src/main/webapp/viewer-html/components/SimpleFilterFilters.js
  viewer/src/main/webapp/viewer-html/components/Snapping.js
Labels: :bomb: bug

#2036 Bump GeoTools 23.2 ➜ 23.3 and b3p-commons-csw 6.2.2 ➜ 6.2.3
  pom.xml
Labels: dependencies, no backport :no_entry:

#2044 [Backport v5.4.x] Dependency backports (mssql-jdbc, apache.httpcomponents, postgresql)
  pom.xml
Labels: dependencies

#2048 Fixes faulty upload in edit component
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: :bomb: bug, backport v5.6.x, hacktoberfest-accepted

#2050 Add the `com.github.eirslett:frontend-maven-plugin` in `dependencyManagment`
  pom.xml
Labels: build infrastructure, dependencies

#2051 Get GBI releases working
  .github/dependabot.yml
  viewer/pom.xml
Labels: build infrastructure, hacktoberfest-accepted

#2055 GBIW-114: form cancel button doesnt work
  viewer-admin/src/main/webapp/WEB-INF/jsp/services/editform.jsp
Labels: :bomb: bug

#2054 Feat/gbiw 170 sewage workflow
  tailormap-components/projects/bridge/typings/Mapcomponents.d.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.html
  tailormap-components/projects/core/src/lib/shared/feature-initializer/feature-initializer.service.ts
  tailormap-components/projects/core/src/lib/shared/formconfig-repository/formconfig-repository.service.ts
  tailormap-components/projects/core/src/lib/user-interface/sewage/choose-types/choose-types.component.css
  tailormap-components/projects/core/src/lib/user-interface/sewage/choose-types/choose-types.component.html
  tailormap-components/projects/core/src/lib/user-interface/sewage/choose-types/choose-types.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/sewage/choose-types/choose-types.component.ts
  tailormap-components/projects/core/src/lib/user-interface/user-interface.module.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-controller/workflow-controller.service.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-factory/workflow-factory.service.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/SewageWorkflow.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/Workflow.ts
Labels: enhancement :+1:

#2083 Fix performance of component configs
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ComponentConfigListActionBean.java
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/LayoutManagerActionBean.java
  viewer-admin/src/main/webapp/WEB-INF/jsp/application/configPage.jsp
  viewer-config-persistence/pom.xml
  viewer/src/main/webapp/viewer-html/components/ConfigObject.js
  viewer/src/main/webapp/viewer-html/components/Cyclorama-config.js
  viewer/src/main/webapp/viewer-html/components/SimpleFilter-config.js
Labels: :bomb: bug, backport v5.6.x

#2075 Feat/gbiw 177 proxy for rest calls
  tailormap-components/projects/core/src/lib/shared/shared.module.ts
  viewer/src/main/java/nl/b3p/viewer/stripes/ProxyRESTActionBean.java
Labels: enhancement :+1:, featurerequest :+1:

#2089 Added columns attribute to filter out columsn for export
  viewer/src/main/java/nl/b3p/viewer/stripes/DownloadFeaturesActionBean.java
Labels: featurerequest :+1:

#2091 Feat/gbiw 196 backend statistic analysis attributelist
  viewer/src/main/java/nl/b3p/viewer/stripes/StatisticAnalysisActionBean.java
Labels: featurerequest :+1:, no backport :no_entry:
