Repository B3Partners/tailormap, pull requests merged in 2020-06, with the labels that each got.

#1833 [Backport v5.6.x] Bump geotools.version from 23.0 to 23.1
  pom.xml
Labels: dependencies

#1837 Load user-details upon IPAuthentication, details is used for isUserEx…
  viewer/src/main/java/nl/b3p/viewer/util/IPAuthenticationFilter.java
Labels: :bomb: bug, backport v5.6.x

#1849 Fixes #1848: prevent NPE when opening configurationscreen of component
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/ConfiguredAttribute.java
Labels: backport v5.4.x, backport v5.6.x

#1853 fix pdok testcase, revert maven-war-plugin update
  pom.xml
  viewer-config-persistence/src/test/java/nl/b3p/viewer/config/services/TileServiceTest.java
Labels: backport v5.4.x, backport v5.6.x, build infrastructure

#1858 Allow setting the label width of attribute labels on the edit form
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en.properties
  viewer/src/main/webapp/viewer-html/components/Edit-config.js
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: enhancement :+1:, featurerequest :+1:, no backport :no_entry:

#1859 make the window that holds the list of edit features wider
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: enhancement :+1:, no backport :no_entry:

#1869 Also order by version, as otherwise the ordering of the resultset is …
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ChooseApplicationActionBean.java
Labels: :bomb: bug, backport v5.4.x, backport v5.6.x

#1880 [Backport v5.4.x] Bump hsqldb from 2.4.1 to 2.5.1 (#1878)
  pom.xml
Labels: build infrastructure, dependencies

#1881 fix xss in ApplicationActionBean
  viewer/src/main/java/nl/b3p/viewer/stripes/ApplicationActionBean.java
Labels: :bomb: bug, backport v5.4.x, backport v5.6.x, security, viewer
