Repository B3Partners/tailormap, pull requests merged in 2020-11, with the labels that each got.

#1894 Mapbox GL viewer
  viewer-admin/src/main/java/nl/b3p/viewer/admin/processes/SPOTinfoTokenRefresher.java
  viewer-admin/src/main/java/nl/b3p/viewer/admin/processes/SPOTinfoTokenRefresherListener.java
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en.properties
  viewer-admin/src/main/webapp/META-INF/context.xml
  viewer-admin/src/main/webapp/WEB-INF/classes/log4j.properties
  viewer-admin/src/main/webapp/WEB-INF/web.xml
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/Application.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/ConfiguredComponent.java
  viewer/src/main/java/nl/b3p/viewer/stripes/ApplicationActionBean.java
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en.properties
  viewer/src/main/webapp/WEB-INF/jsp/app.jsp
  viewer/src/main/webapp/viewer-html/components/MapboxGL-config.js
  viewer/src/main/webapp/viewer-html/components/MapboxGL.js
  viewer/src/main/webapp/viewer-html/components/components.json
  viewer/src/main/webapp/viewer-html/components/resources/css/mapboxGL.css
  viewer/src/main/webapp/viewer-html/components/resources/mapbox-gl/mapbox-gl.css
  viewer/src/main/webapp/viewer-html/components/resources/mapbox-gl/mapbox-gl.js
  viewer/src/main/webapp/viewer-html/components/resources/mapbox-gl/mapbox-gl.js.map
  viewer/src/main/webapp/viewer-html/components/resources/mapbox-gl/version.txt
  viewer/src/main/webapp/viewer-html/sprite.svg
  viewer/src/main/webapp/viewer-html/svg/mapboxgl.svg
Labels: featurerequest :+1:, no backport :no_entry:

#2096 GBIW-201: selecting layers doesn't work entirely
  tailormap-components/projects/bridge/src/tailor-map.service.ts
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/Event.js
  viewer/src/main/webapp/viewer-html/components/TOC.js
Labels: :bomb: bug

#2097 Load "EVRootCA.cer" into certificate store on Travis-CI
  .travis.yml
Labels: backport v5.4.x, backport v5.6.x, build infrastructure

#2104 [mantis 15294] searchconfig loses its layers sometimes
  viewer/src/main/webapp/viewer-html/components/Search-config.js
Labels: :bomb: bug, backport v5.6.x

#2117 removed dead code
  viewer/src/main/webapp/viewer-html/components/GBI-config.js
  viewer/src/main/webapp/viewer-html/components/GBI.js
Labels: enhancement :+1:

#2121 Goodbye Travis-CI, welcome GitHub actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/macos-maven.yml
  .github/workflows/ubuntu-maven.yml
  .travis.yml
  .travis/settings.xml
  README.md
  codecov.yml
  pom.xml
  viewer-admin/pom.xml
  viewer-commons/docker/geoserver/docker-compose.yml
  viewer/pom.xml
Labels: backport v5.4.x, backport v5.6.x, build infrastructure, featurerequest :+1:, viewer, viewer-admin

#2124 [Backport 5.6.x] Goodbye Travis-CI, welcome GitHub actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/macos-maven.yml
  .github/workflows/ubuntu-maven.yml
  .travis.yml
  .travis/settings.xml
  README.md
  codecov.yml
  pom.xml
  viewer-admin/pom.xml
  viewer-commons/docker/geoserver/docker-compose.yml
  viewer/pom.xml
Labels: backport v5.4.x, build infrastructure, viewer, viewer-admin

#2123 [Bug] Fix switching on layers via search doesn't work
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
  viewer/src/main/webapp/viewer-html/components/TOC.js
Labels: backport v5.4.x, backport v5.6.x, viewer

#2129 Feat/gbiw 254 255 230 highlight zoomto
  tailormap-components/projects/bridge/typings/Components.d.ts
  tailormap-components/projects/bridge/typings/Mapcomponents.d.ts
  tailormap-components/projects/core/src/lib/shared/feature-extent-service/feature-extent-models.ts
  tailormap-components/projects/core/src/lib/shared/feature-extent-service/feature-extent.service.spec.ts
  tailormap-components/projects/core/src/lib/shared/feature-extent-service/feature-extent.service.ts
  tailormap-components/projects/core/src/lib/shared/highlight-service/highlight-models.ts
  tailormap-components/projects/core/src/lib/shared/highlight-service/highlight.service.spec.ts
  tailormap-components/projects/core/src/lib/shared/highlight-service/highlight.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-models.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-panel/attributelist-panel.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-table/attributelist-table.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/layer.service.ts
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersVectorLayer.js
  viewer/src/main/webapp/viewer-html/components/NgAttributeList.js
Labels: viewer
