Repository B3Partners/tailormap, pull requests merged in 2020-02, with the labels that each got.

#1683 Support for geofenceheader
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/GeoServiceActionBean.java
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/webapp/WEB-INF/jsp/services/geoservice.jsp
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/GeoService.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/databaseupdate/DatabaseSynchronizer.java
  viewer-config-persistence/src/main/resources/scripts/hsqldb-add_geoservice_geofence_header.sql
  viewer-config-persistence/src/main/resources/scripts/microsoft_sql_server-add_geoservice_geofence_header.sql
  viewer-config-persistence/src/main/resources/scripts/oracle-add_geoservice_geofence_header.sql
  viewer-config-persistence/src/main/resources/scripts/postgresql-add_geoservice_geofence_header.sql
  viewer-config-persistence/src/test/resources/nl/b3p/viewer/util/testdata.sql
  viewer/src/main/java/nl/b3p/viewer/stripes/ProxyActionBean.java
Labels: enhancement :+1:, viewer

#1684 tune travis-ci config
  .travis.yml
Labels: backport v5.4.x, backport v5.6.x, build infrastructure

#1689 Include the Oracle ojdbc8 database driver in the Tomcat lib package
  pom.xml
  tomcat-lib/README.md
  tomcat-lib/assembly.xml
  tomcat-lib/pom.xml
Labels: backport v5.6.x, dependencies

#1688 User isn't able to save the configuration when the layers aren't load…
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en.properties
  viewer-admin/src/main/webapp/resources/js/layoutmanager/configPage.js
  viewer-admin/src/main/webapp/resources/js/ux/b3p/FilterableCheckboxes.js
  viewer/src/main/webapp/viewer-html/components/AttributeList-config.js
  viewer/src/main/webapp/viewer-html/components/ConfigObject.js
Labels: :bomb: bug, backport v5.6.x

#1693 [Backport v5.6.x] Include the Oracle ojdbc8 database driver
  pom.xml
  tomcat-lib/README.md
  tomcat-lib/assembly.xml
  tomcat-lib/pom.xml
Labels: dependencies

#1698 Check if layer isn't null
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/GeoServiceActionBean.java
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en.properties
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/TileService.java
Labels: :bomb: bug, backport v5.4.x, backport v5.6.x

#1696 Limit the number of features to be downloaded
  viewer/src/main/java/nl/b3p/viewer/stripes/DownloadFeaturesActionBean.java
  viewer/src/main/webapp/META-INF/context.xml
Labels: backport v5.4.x, backport v5.6.x

#1695 Prevent a possible NPE by checking for a null valued serviceId in the ProxyActionBean
  viewer/src/main/java/nl/b3p/viewer/stripes/ProxyActionBean.java
Labels: :bomb: bug, backport v5.6.x

#1701 IE11 hack for undefined error when you have simple filters that are set during startup
  viewer/src/main/webapp/viewer-html/common/ajax/SLD.js
Labels: :bomb: bug, backport v5.6.x

#1707 only use port 9090 for tomcat during tests
  Jenkinsfile
  viewer-admin/pom.xml
  viewer-admin/src/test/java/nl/b3p/viewer/admin/ViewerAdminLockoutIntegrationTest.java
Labels: backport v5.2.x, backport v5.4.x, backport v5.6.x, build infrastructure

#1712 Bump Tomcat test dependencies 7.0.99 ⇨ 7.0.100
  pom.xml
Labels: backport v5.4.x, backport v5.6.x, build infrastructure, dependencies, security
