Repository B3Partners/tailormap, pull requests merged in 2020-09, with the labels that each got.

#1968 Fixes #GBIW-129: label collapses and expands treenode
  viewer/src/main/webapp/flamingo-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.html
Labels: enhancement :+1:

#1959 Added service for retrieving metadata and data for layers/featuretypes
  tailormap-components/package-lock.json
  tailormap-components/projects/core/src/lib/user-interface/user-interface.module.ts
  viewer/src/main/webapp/flamingo-components/projects/core/src/lib/shared/attribute-service/attribute-list-service.service.spec.ts
  viewer/src/main/webapp/flamingo-components/projects/core/src/lib/shared/attribute-service/attribute.service.ts
  viewer/src/main/webapp/flamingo-components/projects/core/src/lib/user-interface/test-attributeservice/models.ts
  viewer/src/main/webapp/flamingo-components/projects/core/src/lib/user-interface/test-attributeservice/test-attributeservice.component.css
  viewer/src/main/webapp/flamingo-components/projects/core/src/lib/user-interface/test-attributeservice/test-attributeservice.component.html
  viewer/src/main/webapp/flamingo-components/projects/core/src/lib/user-interface/test-attributeservice/test-attributeservice.component.spec.ts
  viewer/src/main/webapp/flamingo-components/projects/core/src/lib/user-interface/test-attributeservice/test-attributeservice.component.ts
Labels: featurerequest :+1:

#1990 Feat/gbiw 142 codecov
  .github/workflows/angular-components.yml
  tailormap-components/projects/core/src/lib/feature-form/form/form-helpers.spec.ts
Labels: build infrastructure, no backport :no_entry:

#1991 Moved subscription of layervisibilitychanged event to after angular i…
  viewer/src/main/webapp/viewer-html/components/GBI.js
Labels: :bomb: bug

#1956 Add a docker module to build a docker image
  .gitignore
  Jenkinsfile
  docker/README.md
  docker/pom.xml
  docker/src/main/docker/Dockerfile
  docker/src/main/docker/tomcat_conf/Catalina/localhost/solr.xml
  docker/src/main/docker/tomcat_conf/Catalina/localhost/viewer-admin.xml
  docker/src/main/docker/tomcat_conf/Catalina/localhost/viewer.xml
  docker/src/main/docker/tomcat_conf/server.xml
  pom.xml
  tomcat-lib/assembly.xml
Labels: Hacktoberfest :beers:, featurerequest :+1:, no backport :no_entry:, task

#2001 Bug/gbiw 133 repopulate form after save
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-field/form-field-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form-models.ts
Labels: :bomb: bug, enhancement :+1:

#2008 Fixes #2007: DOMException thrown when run in iframe
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
Labels: :bomb: bug, backport v5.4.x, backport v5.6.x

#1983 Upgrade GeoTools to 24.0
  pom.xml
Labels: dependencies, no backport :no_entry:

#2014 disable saving the configuration before everything is loaded
  viewer/src/main/webapp/viewer-html/components/Search-config.js
Labels: :bomb: bug, backport v5.4.x, backport v5.6.x

#2017 Feat/gbiw 162 demo fixes
  tailormap-components/projects/core/src/lib/feature-form/form-popup/form-popup-models.ts
  tailormap-components/projects/core/src/lib/feature-form/form-popup/form-popup.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/shared/feature-initializer/feature-initializer.service.ts
  tailormap-components/projects/core/src/lib/shared/generated/models/page-weginspectie.ts
  tailormap-components/projects/core/src/lib/shared/generated/models/weginspectie.ts
  tailormap-components/projects/core/src/lib/shared/generated/services/weginspectie-controller.service.ts
  viewer/src/main/webapp/viewer-html/components/GBI.js
Labels: enhancement :+1:
