Repository B3Partners/tailormap, pull requests merged in 2020-05, with the labels that each got.

#1811 [Backport v5.6.x] New Jenkins + dockerized oracle-xe (#1810)
  .jenkins/clear-oracle-schema.sql
  .jenkins/create_oracle_user.sql
  .jenkins/start-oracle.sh
  .travis/settings.xml
  Jenkinsfile
  pom.xml
  viewer-admin/src/test/resources/oracle.properties
  viewer/src/test/resources/oracle.properties
Labels: build infrastructure

#1812 [Backport v5.4.x] New Jenkins + dockerized oracle-xe (#1810)
  .jenkins/clear-oracle-schema.sql
  .jenkins/create_oracle_user.sql
  .jenkins/start-oracle.sh
  .travis/settings.xml
  Jenkinsfile
  pom.xml
  viewer-admin/pom.xml
  viewer-admin/src/test/resources/oracle.properties
  viewer/pom.xml
  viewer/src/test/resources/oracle.properties
Labels: build infrastructure

#1809 geometry_columns do not exist in oracle
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/JDBCFeatureSource.java
Labels: :bomb: bug

#1817 Bump Tomcat libs 7.0.103 -> 7.0.104
  pom.xml
Labels: backport v5.4.x, backport v5.6.x, security

#1828 Use in-memory hsqldb for unittests
  Jenkinsfile
  viewer-config-persistence/src/test/java/nl/b3p/viewer/util/TestUtil.java
Labels: backport v5.4.x, backport v5.6.x, build infrastructure

#1830 [Backport v5.4.x] Use in-memory hsqldb for unittests
  viewer-config-persistence/src/test/java/nl/b3p/viewer/util/TestUtil.java
Labels: build infrastructure

#1816 backport from @mprins. Arrowfunctions not in ie11, so revert this epi…
  viewer/src/main/webapp/viewer-html/components/Snapping.js
Labels: :bomb: bug

#1825 Remnant of #1623: update related entities for featuretype
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/AttributeSourceActionBean.java
Labels: :bomb: bug, backport v5.4.x
