Repository B3Partners/tailormap, pull requests merged in 2020-07, with the labels that each got.

#1885 Better user error message on edit fail
  viewer/src/main/java/nl/b3p/viewer/stripes/EditFeatureActionBean.java
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en.properties
  viewer/src/main/webapp/error.jsp
Labels: backport v5.6.x, enhancement :+1:, featurerequest :+1:

#1886 Fix Oracle syntax error in upgrade script
  viewer-config-persistence/src/main/resources/scripts/oracle-automatic_attributes.sql
Labels: :bomb: bug, backport v5.4.x, backport v5.6.x

#1891 Update OWASP suppressions
  .mvn/owasp-suppression.xml
Labels: backport v5.4.x, backport v5.6.x, build infrastructure, task

#1882 use cookie for session tracking
  viewer/src/main/webapp/WEB-INF/web.xml
Labels: backport v5.4.x, backport v5.6.x, security, viewer

#1899 configuration option for the maximum amount of features in the download functionality of the attributelist
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en.properties
  viewer/src/main/java/nl/b3p/viewer/stripes/DownloadFeaturesActionBean.java
  viewer/src/main/webapp/META-INF/context.xml
  viewer/src/main/webapp/viewer-html/components/AttributeList-config.js
Labels: backport v5.6.x, enhancement :+1:

#1898 Bug/performance layer list
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/ApplicationLayer.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/databaseupdate/DatabaseSynchronizer.java
  viewer-config-persistence/src/test/resources/nl/b3p/viewer/util/testdata.sql
  viewer/src/main/webapp/viewer-html/common/ajax/LayerSelector.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
  viewer/src/main/webapp/viewer-html/components/FeatureReport.js
  viewer/src/main/webapp/viewer-html/components/Print.js
  viewer/src/main/webapp/viewer-html/components/SimpleFilterFilters.js
  viewer/src/main/webapp/viewer-html/components/Snapping.js
Labels: :bomb: bug, backport v5.6.x, enhancement :+1:
