Repository B3Partners/tailormap, pull requests merged in 2020-01, with the labels that each got.

#1647 Raise base level of z-indices, so other layers don't interrupt with v…
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersMapComponent.js
Labels: :bomb: bug

#1653 Add a generic error page to prevent unwanted information disclosure
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en.properties
  viewer/src/main/webapp/WEB-INF/web.xml
  viewer/src/main/webapp/error.jsp
Labels: featurerequest :+1:, security

#1657 [Backport v5.6.x] Bump geotools.version from 22.1 to 22.2
  pom.xml
Labels: dependencies

#1658 Make minimum password length configurable
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/UserActionBean.java
  viewer-admin/src/main/webapp/WEB-INF/web.xml
Labels: backport v5.6.x, security

#1662 Bump org.apache.tika:tika-core 1.22 -> 1.23
  pom.xml
Labels: backport v5.6.x, dependencies

#1664 update error codes to trap in the generic page
  viewer/src/main/java/nl/b3p/viewer/stripes/ComponentActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/FeatureReportActionBean.java
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en.properties
  viewer/src/main/webapp/WEB-INF/web.xml
  viewer/src/main/webapp/error.jsp
Labels: featurerequest :+1:, security

#1655 fix session id exposure in DownloadMap
  viewer/src/main/java/nl/b3p/viewer/stripes/CombineImageActionBean.java
  viewer/src/main/webapp/viewer-html/common/ajax/CombineImage.js
  viewer/src/main/webapp/viewer-html/components/DownloadMap.js
Labels: backport v5.6.x, security

#1667 Always add layers/levels to appconfig.levels and appconfig.applayers.…
  viewer-config-persistence/src/main/java/nl/b3p/viewer/util/SelectedContentCache.java
Labels: :bomb: bug, backport v5.6.x
