Repository B3Partners/tailormap, pull requests merged in 2021-02, with the labels that each got.

#2302 stopclick events when drawing polygon
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/OlVectorLayer.js
Labels: :bomb: bug, viewer

#2305 added option to show line length of every line in a polygon
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en.properties
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/VectorLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersVectorLayer.js
  viewer/src/main/webapp/viewer-html/components/Edit-config.js
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: enhancement :+1:, featurerequest :+1:, viewer, viewer-admin

#2306 changed list entries of events to single events with configuration
  .github/workflows/angular-components-deployment.yml
  .github/workflows/angular-components.yml
  .github/workflows/macos-maven.yml
  .github/workflows/ubuntu-maven.yml
  tailormap-components/projects/core/src/lib/workflow/workflows/EditgeometryWorkflow.ts
Labels: build infrastructure, viewer

#2308 fix Update script 'add_form-readers.sql' nor 'microsoft_sql_server-add_form-readers.sql' can be found
  viewer-config-persistence/src/main/resources/scripts/microsoft_sql_server-add_form-readers.sql
Labels: :bomb: bug, viewer-config-persistence

#2320 [Backport v5.4.x] Bump tomcat.version from 7.0.107 to 7.0.108 (#2318)
  pom.xml
Labels: build infrastructure, dependencies

#2309 Refactor van audit module
  viewer-audit/pom.xml
  viewer-audit/src/main/java/nl/b3p/viewer/audit/AuditMessageObject.java
  viewer-audit/src/main/java/nl/b3p/viewer/audit/Auditable.java
Labels: featurerequest :+1:, java11

#2321 update libs
  tailormap-components/package-lock.json
  tailormap-components/package.json
Labels: viewer

#2322 Javadoc fixes
  Jenkinsfile
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/I18nActionBean.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/Application.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/ApplicationLayer.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/UpdatableFeatureSource.java
Labels: java, no backport :no_entry:, viewer-admin, viewer-config-persistence

#2324 Dev/details component refactoring
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-content/attribute-list-tab-content.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-details/attributelist-details.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-details/attributelist-details.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/models/attribute-list-filter.model.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-manager.service.ts
  tailormap-components/projects/core/src/lib/user-interface/panel-resizer/panel-resizer.component.ts
Labels: viewer

#2323 gebruik een kleinere oracle-xe docker image
  .jenkins/create_oracle_user.sql
  .jenkins/start-oracle.sh
Labels: backport v5.4.x, backport v5.6.x, build infrastructure

#2330 Bug fix/form copy component
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.ts
Labels: :bomb: bug, viewer

#2340 Remove Jenkins, GH and Appveyor configs, this branch (v5.4.x) has no active development and no longer needs any CI
  .appveyor/set-maven-proxy.ps1
  .github/workflows/ubuntu-maven.yml
  .jenkins/clear-oracle-schema.sql
  .jenkins/create_oracle_user.sql
  .jenkins/insert-fla-version.sh
  .jenkins/start-oracle.sh
  Jenkinsfile
  appveyor.yml
Labels: build infrastructure

#2341 change style of buttons in formcopy component
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.html
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.css
Labels: viewer

#2342 Bugfix: not showing value for field in form when not editting
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.html
Labels: viewer

#2350 Bugs/form edits
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.html
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.css
Labels: viewer

#2352 15882: retrieve features for the form tree from the state
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.css
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.html
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.actions.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.effects.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.reducer.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.selectors.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.state.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
Labels: backport v5.8.x, viewer

#2344 Gebruik Node v14.15.5 voor de Maven builds
  pom.xml
  viewer/pom.xml
Labels: backport v5.8.x, build infrastructure, viewer

#2353 15895: Show attribute-list on top of other components when maximized
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list/attribute-list.component.css
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/add-feature-menu/add-feature-menu.component.ts
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/edit-bar/edit-bar.component.css
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/edit-bar/edit-bar.component.html
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/edit-bar/edit-bar.component.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-controller/workflow-controller.component.css
  tailormap-components/projects/core/src/lib/workflow/workflow-controller/workflow-controller.component.html
  tailormap-components/projects/core/src/lib/workflow/workflow-controller/workflow-controller.component.ts
Labels: backport v5.8.x, viewer

#2361 [Backport v5.6.x] Bump postgresql from 42.2.18 to 42.2.19
  pom.xml
Labels: dependencies

#2343 Produceer Java 11 artifacts
  .github/workflows/ubuntu-maven.yml
  Jenkinsfile
  docker/pom.xml
  pom.xml
  viewer-admin/pom.xml
  viewer-commons/pom.xml
  viewer/pom.xml
Labels: build infrastructure, dependencies, no backport :no_entry:, viewer, viewer-admin

#2363 Java 8 classfiles als compiler output
  .jenkins/check-java-binary-version.sh
  Jenkinsfile
  pom.xml
Labels: backport v5.6.x, build infrastructure

#2362 Move FormConfigs to Application state
  tailormap-components/projects/core/src/lib/application/services/application.service.ts
  tailormap-components/projects/core/src/lib/application/services/metadata.service.ts
  tailormap-components/projects/core/src/lib/application/state/application.actions.ts
  tailormap-components/projects/core/src/lib/application/state/application.reducer.ts
  tailormap-components/projects/core/src/lib/application/state/application.selectors.ts
  tailormap-components/projects/core/src/lib/application/state/application.state.ts
  tailormap-components/projects/core/src/lib/application/state/test-data/application-test-data.ts
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.spec.ts
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.spec.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.spec.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.html
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.spec.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/linked-fields/domain-repository/domain-repository.service.spec.ts
  tailormap-components/projects/core/src/lib/feature-form/linked-fields/domain-repository/domain-repository.service.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.actions.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.reducer.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.selectors.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.state.ts
  tailormap-components/projects/core/src/lib/feature-form/state/test-data/form-test-data.ts
  tailormap-components/projects/core/src/lib/shared/attribute-service/attribute.service.ts
  tailormap-components/projects/core/src/lib/shared/formconfig-repository/form-config-repository.service.ts
  tailormap-components/projects/core/src/lib/shared/formconfig-repository/formconfig-mock.module.spec.ts
  tailormap-components/projects/core/src/lib/shared/formconfig-repository/formconfig-repository.service.spec.ts
  tailormap-components/projects/core/src/lib/shared/formconfig-repository/formconfig-repository.service.ts
  tailormap-components/projects/core/src/lib/state/root-state.model.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-column-selection/attribute-list-column-selection.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-column-selection/attribute-list-column-selection.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-details/attribute-list-details.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-data.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-manager.service.ts
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/add-feature-menu/add-feature-menu.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/add-feature-menu/add-feature-menu.component.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/input-field/input-field.component.html
  tailormap-components/projects/core/src/lib/user-interface/generic-components/input-field/input-field.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/label-field/label-field.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/panel-resizer/panel-resizer.component.spec.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-controller/workflow-controller.component.spec.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-factory/workflow-factory.service.spec.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-factory/workflow-factory.service.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/EditgeometryWorkflow.spec.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/Workflow.ts
Labels: backport v5.8.x, viewer

#2365 15905: Create user layer from attribute list
  tailormap-components/projects/core/src/lib/analysis/services/mocks/user-layer.service.mock.ts
  tailormap-components/projects/core/src/lib/analysis/services/user-layer.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.html
Labels: backport v5.8.x, viewer

#2354 15882: Creating new object fixed
  tailormap-components/projects/core/src/lib/feature-form/form-actions/form-actions.service.mock.ts
  tailormap-components/projects/core/src/lib/feature-form/form-actions/form-actions.service.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.spec.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.html
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.actions.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.reducer.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.selectors.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.state.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.effects.ts
Labels: backport v5.8.x, build infrastructure, viewer, viewer-admin, viewer-config-persistence

#2366 15904: Reset checked features after filter reset
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.reducer.ts
Labels: backport v5.8.x, viewer

#2393 15929: remove unsaved features from tree
  tailormap-components/package-lock.json
  tailormap-components/projects/core/src/lib/feature-form/state/form.reducer.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.state-helpers.ts
Labels: backport v5.8.x, viewer
