Repository B3Partners/tailormap, pull requests merged in 2021-05, with the labels that each got.

#2674 Bump NodeJS from v14.15.5 to v14.16.1 for Maven builds
  pom.xml
Labels: backport v5.8.x, build infrastructure

#2678 Prevent duplicate getCount request for attribute list
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-data.service.ts
Labels: viewer

#2687 fixed bug where the sewageworkflow didn't create a duct: the feature …
  tailormap-components/projects/core/src/lib/workflow/workflows/SewageWorkflow.ts
Labels: :bomb: bug, viewer

#2688 Port/sewage workflow doesnt create ducts
  tailormap-components/projects/core/src/lib/workflow/workflows/SewageWorkflow.ts
Labels: viewer

#2692 fix pom files
  pom.xml
  viewer-admin/pom.xml
  viewer-commons/pom.xml
  viewer-config-persistence/pom.xml
  viewer-helpers/pom.xml
Labels: viewer-admin, viewer-config-persistence

#2649 TM-24: Use observable to set the parent value on the the FormGroup
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
  tailormap-components/projects/core/src/lib/feature-form/linked-fields/registry/linked-attribute-registry.service.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2695 TM-143: Show checkboxes for deeper related levels
  tailormap-components/projects/core/src/lib/shared/attribute-service/attribute-models.ts
  tailormap-components/projects/core/src/lib/shared/attribute-service/mocks/attribute.service.mock.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/helpers/attribute-list-filter.helper.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/helpers/attribute-list-filter.helper.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/models/attribute-list-feature-type-data.model.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-manager.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.reducer.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.reducer.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.selectors.ts
  viewer-config-persistence/src/main/java/nl/viewer/config/services/FeatureTypeRelation.java
  viewer-config-persistence/src/main/java/nl/viewer/config/services/SimpleFeatureType.java
  viewer-config-persistence/src/main/resources/scripts/hsqldb-add_featuretypePK.sql
  viewer-config-persistence/src/main/resources/scripts/microsoft_add_featuretypePK.sql
  viewer-config-persistence/src/main/resources/scripts/oracle-add_featuretypePK.sql
  viewer-config-persistence/src/main/resources/scripts/postgresql-add_featuretypePK.sql
  viewer-config-persistence/src/test/resources/nl/viewer/util/testdata.sql
  viewer-helpers/src/main/java/nl/viewer/helpers/app/ApplicationLayerHelper.java
  viewer-helpers/src/main/java/nl/viewer/helpers/featuresources/JDBCFeatureSourceHelper.java
  viewer-helpers/src/main/java/nl/viewer/helpers/featuresources/WFSFeatureSourceHelper.java
  viewer-helpers/src/main/java/nl/viewer/util/databaseupdate/DatabaseSynchronizer.java
Labels: featurerequest :+1:, no backport :no_entry:, viewer, viewer-config-persistence

#2699 Merge pull request #2649 from B3Partners/bugfix/TM-24-set-parentField…
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
  tailormap-components/projects/core/src/lib/feature-form/linked-fields/registry/linked-attribute-registry.service.ts
Labels: viewer
