Repository B3Partners/tailormap, pull requests merged in 2021-11, with the labels that each got.

#2959 fix for failing reactorModuleConvergence enforcer rule
  .github/workflows/ubuntu-maven.yml
  Jenkinsfile
  tailormap-components/package.json
Labels: build infrastructure, viewer

#2961 GBIM-222: Fixes form validation (mandatory, readonly, domain validation)
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-field/form-field-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.html
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/linked-fields/domain-repository/domain-repository.service.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/checkbox-field/checkbox-field.component.html
  tailormap-components/projects/core/src/lib/user-interface/generic-components/datepicker-field/datepicker-field.component.css
  tailormap-components/projects/core/src/lib/user-interface/generic-components/datepicker-field/datepicker-field.component.html
  tailormap-components/projects/core/src/lib/user-interface/generic-components/datepicker-field/datepicker-field.component.ts
Labels: viewer

#2962 GBIM-227: Allow for bulk editing all features from attribute list
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/core/src/lib/application/state/application.actions.ts
  tailormap-components/projects/core/src/lib/feature-form/form-attribute-list-button/form-attribute-list-button.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-attribute-list-button/form-attribute-list-button.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-attribute-list-button/form-attribute-list-button.component.spec.ts
  tailormap-components/projects/core/src/lib/feature-form/form-attribute-list-button/form-attribute-list-button.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.css
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.html
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.actions.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.effects.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.reducer.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.selectors.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.state.ts
  tailormap-components/projects/core/src/lib/shared/tests/test-mocks.ts
Labels: viewer

#2940 Bump `de.jpdigital:hibernate54-ddl-maven-plugin:2.3.0` to `de.jpdigital:hibernate56-ddl-maven-plugin:2.5.0`
  pom.xml
  viewer-config-persistence/pom.xml
Labels: build infrastructure, hacktoberfest, no backport :no_entry:, hacktoberfest-accepted, viewer-config-persistence

#2972 GBIM-231: Create userlayer criteria for nested relations
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/helpers/criteria.helper.ts
  tailormap-components/projects/core/src/lib/analysis/models/criteria-condition.model.ts
Labels: viewer

#2970 GBIM-230: Fix copying nested related features
  tailormap-components/projects/core/src/lib/feature-form/form-actions/form-actions.service.ts
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.service.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
Labels: viewer

#2977 Jakarta mail bump
  .github/dependabot.yml
  docker/src/main/docker/Dockerfile
  pom.xml
Labels: build infrastructure, dependencies

#2973 GBIM-189: Allow to select unique values when creating userlayer criteria
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria-description/criteria-description.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.html
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.ts
  tailormap-components/projects/core/src/lib/shared/value-service/value.service.ts
Labels: viewer
