Repository B3Partners/tailormap, pull requests merged in 2021-08, with the labels that each got.

#2826 Update node dependencies
  tailormap-components/package-lock.json
  tailormap-components/package.json
Labels: build infrastructure, dependencies, javascript, viewer

#2828 forbid use of Junit 4, simplify dependencies
  pom.xml
  viewer-commons/pom.xml
  viewer/src/test/java/nl/tailormap/viewer/userlayer/UserLayerHandlerIntegrationTest.java
Labels: build infrastructure, dependencies, viewer

#2834 [TM-260] make SelectedContentCache and persitence module less interwoven with Servlet API
  viewer-admin/src/main/java/nl/tailormap/viewer/admin/stripes/ServiceUsageMatrixActionBean.java
  viewer-admin/src/main/java/nl/tailormap/viewer/admin/stripes/UserActionBean.java
  viewer-admin/src/main/webapp/WEB-INF/jsp/security/authorizations.jsp
  viewer-config-persistence/pom.xml
  viewer-config-persistence/src/main/java/nl/tailormap/viewer/config/app/Application.java
  viewer-config-persistence/src/main/java/nl/tailormap/viewer/config/app/Level.java
  viewer-config-persistence/src/main/java/nl/tailormap/viewer/config/security/Authorizations.java
  viewer-config-persistence/src/main/java/nl/tailormap/viewer/config/services/ArcGISService.java
  viewer-config-persistence/src/main/java/nl/tailormap/viewer/config/services/GeoService.java
  viewer-config-persistence/src/main/java/nl/tailormap/viewer/config/services/TileService.java
  viewer-helpers/src/main/java/nl/tailormap/viewer/helpers/AuthorizationsHelper.java
  viewer-helpers/src/main/java/nl/tailormap/viewer/helpers/app/ApplicationHelper.java
  viewer-helpers/src/main/java/nl/tailormap/viewer/helpers/app/LevelHelper.java
  viewer-helpers/src/main/java/nl/tailormap/viewer/helpers/featuresources/FeatureSourceFactoryHelper.java
  viewer-helpers/src/main/java/nl/tailormap/viewer/helpers/services/ArcGISServiceHelper.java
  viewer-helpers/src/main/java/nl/tailormap/viewer/helpers/services/GeoServiceHelper.java
  viewer-helpers/src/main/java/nl/tailormap/viewer/helpers/services/LayerHelper.java
  viewer-helpers/src/main/java/nl/tailormap/viewer/helpers/services/TilingServiceHelper.java
  viewer-helpers/src/main/java/nl/tailormap/viewer/util/SelectedContentCache.java
  viewer-helpers/src/test/java/nl/tailormap/viewer/config/services/TileServiceTest.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/ApplicationActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/ArcQueryUtilActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/AttributesActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/CatalogSearchActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/ComponentActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/DownloadFeaturesActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/EditFeatureActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/FeatureExtentActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/FeatureInfoActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/FeatureReportActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/FileUploadActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/FormActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/GeoServiceRegistryActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/LayerListActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/MergeFeaturesActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/ProxyActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/ServiceActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/SimplifyFeatureActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/SplitFeatureActionBean.java
  viewer/src/main/java/nl/tailormap/viewer/stripes/UserLayerActionBean.java
Labels: viewer-admin, viewer, viewer-config-persistence

#2853 Dev changes
  pom.xml
  tailormap-components-config/angular.json
  tailormap-components-config/package-lock.json
  tailormap-components-config/package.json
  tailormap-components/angular.json
  tailormap-components/package-lock.json
  tailormap-components/package.json
Labels: viewer

#2858 geen npm packages meer updaten, teveel lawaai
  .github/dependabot.yml
Labels: build infrastructure

#2857 add "default_application" to test data
  viewer-config-persistence/src/test/resources/nl/tailormap/viewer/util/testdata.sql
Labels: viewer-config-persistence, no backport :no_entry:

#2862 Updated @tailormap packages
  package.json
  tailormap-components-config/package-lock.json
  tailormap-components-config/package.json
  tailormap-components/angular.json
  tailormap-components/bin/merge-assets-angular.js
  tailormap-components/package-lock.json
  tailormap-components/package.json
Labels: viewer, javascript

#2864 Update @tailormap/models and provide API_BASE_URL
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/bridge/src/environments/environment.prod.ts
  tailormap-components/projects/bridge/src/environments/environment.ts
  tailormap-components/projects/core/src/lib/core.module.ts
  viewer/src/main/webapp/WEB-INF/jsp/app.jsp
Labels: viewer

#2867 dependency version bumps
  pom.xml
Labels: build infrastructure, dependencies

#2870 Use new @tailormap/api package instead of @tailormap/models
  tailormap-components-config/package-lock.json
  tailormap-components-config/package.json
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/core/src/lib/analysis/analysis-attribute-list-button/analysis-attribute-list-button.component.ts
  tailormap-components/projects/core/src/lib/analysis/attribute-selector/attribute-selector.component.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-layer-selection/create-layer-layer-selection.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria-description/criteria-description.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.ts
  tailormap-components/projects/core/src/lib/analysis/services/create-style.service.ts
  tailormap-components/projects/core/src/lib/application/services/application.service.ts
  tailormap-components/projects/core/src/lib/application/services/metadata.service.ts
  tailormap-components/projects/core/src/lib/application/services/mocks/metadata.service.mock.ts
  tailormap-components/projects/core/src/lib/core.module.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/shared/attribute-service/attribute.service.ts
  tailormap-components/projects/core/src/lib/shared/export-service/export.service.ts
  tailormap-components/projects/core/src/lib/shared/feature-selection/feature-selection.service.ts
  tailormap-components/projects/core/src/lib/shared/highlight-service/highlight.service.ts
  tailormap-components/projects/core/src/lib/shared/statistic-service/statistic.service.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-factory/workflow-factory.service.spec.ts
  tailormap-components/projects/third-party-components/package.json
Labels: viewer

#2880 Dependency updates
  pom.xml
Labels: build infrastructure, security, dependencies
