Repository B3Partners/tailormap, pull requests merged in 2021-04, with the labels that each got.

#2505 15972: Filter options inside resolution selector based on min/max
  tailormap-components/projects/core/src/lib/analysis/analysis.module.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-styling/create-layer-styling.component.html
  tailormap-components/projects/core/src/lib/analysis/resolution-range-selector/resolution-range-selector.component.css
  tailormap-components/projects/core/src/lib/analysis/resolution-range-selector/resolution-range-selector.component.html
  tailormap-components/projects/core/src/lib/analysis/resolution-range-selector/resolution-range-selector.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/resolution-range-selector/resolution-range-selector.component.ts
  tailormap-components/projects/core/src/lib/analysis/resolution-selector/resolution-selector.component.html
  tailormap-components/projects/core/src/lib/analysis/resolution-selector/resolution-selector.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/resolution-selector/resolution-selector.component.ts
  tailormap-components/projects/core/src/lib/analysis/style-form/style-form.component.html
  viewer/src/main/webapp/WEB-INF/jsp/app.jsp
Labels: backport v5.8.x, viewer

#2506 15993: Refactor statistics by moving stats to the state + refresh after changing filters
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-statistics-menu/attribute-list-statistics-menu.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-statistics-menu/attribute-list-statistics-menu.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-statistics-menu/attribute-list-statistics-menu.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-statistics-menu/attribute-list-statistics-menu.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list.module.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-statistic-models.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-statistic.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/helpers/attribute-list-filter.helper.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/helpers/statistics-helper.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/models/attribute-list-feature-type-data.model.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/models/attribute-list-statistic-column.model.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-data.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-manager.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.actions.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.effects.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.reducer.ts
Labels: backport v5.8.x, viewer

#2508 15886: Add use selected layer config for workflow
  tailormap-components/projects/core/src/lib/shared/feature-selection/feature-selection.component.spec.ts
  tailormap-components/projects/core/src/lib/shared/layer-utils/layer-utils.service.spec.ts
  tailormap-components/projects/core/src/lib/shared/layer-utils/layer-utils.service.ts
  tailormap-components/projects/core/src/lib/workflow/state/workflow.actions.ts
  tailormap-components/projects/core/src/lib/workflow/state/workflow.reducer.ts
  tailormap-components/projects/core/src/lib/workflow/state/workflow.selectors.ts
  tailormap-components/projects/core/src/lib/workflow/state/workflow.state.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-controller/workflow-controller.component.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en.properties
  viewer/src/main/webapp/viewer-html/components/GBI-config.js
  viewer/src/main/webapp/viewer-html/components/GBI.js
Labels: viewer, viewer-admin

#2521 16015: Allow to create user layers from layers without passport
  tailormap-components/projects/core/src/lib/analysis/attribute-selector/attribute-selector.component.html
  tailormap-components/projects/core/src/lib/analysis/attribute-selector/attribute-selector.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/attribute-selector/attribute-selector.component.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-mode-thematic/create-layer-mode-thematic.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria-description/criteria-description.component.css
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria-description/criteria-description.component.html
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.ts
  tailormap-components/projects/core/src/lib/analysis/models/create-layer-data.model.ts
  tailormap-components/projects/core/src/lib/analysis/services/create-style.service.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.actions.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.reducer.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.selectors.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.state.ts
  tailormap-components/projects/core/src/lib/analysis/state/test-data/analysis-test-data.ts
  tailormap-components/projects/core/src/lib/application/models/extended-attribute.model.ts
  tailormap-components/projects/core/src/lib/application/models/passport-attribute.model.ts
  tailormap-components/projects/core/src/lib/application/services/metadata.service.ts
  tailormap-components/projects/core/src/lib/application/services/mocks/metadata.service.mock.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-manager.service.ts
Labels: viewer

#2510 Implement stricter linting: No unused vars / locals
  tailormap-components/.eslintrc.json
  tailormap-components/projects/bridge/src/tailor-map.service.ts
  tailormap-components/projects/bridge/tsconfig.spec.json
  tailormap-components/projects/core/src/lib/analysis/analysis-button/analysis-button.component.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.effects.ts
  tailormap-components/projects/core/src/lib/application/services/application.service.ts
  tailormap-components/projects/core/src/lib/application/services/metadata.service.ts
  tailormap-components/projects/core/src/lib/feature-form/feature-form.module.ts
  tailormap-components/projects/core/src/lib/feature-form/form-actions/form-actions.service.ts
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/linked-fields/domain-repository/domain-repository.service.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.effects.ts
  tailormap-components/projects/core/src/lib/shared/popover/popover.service.ts
  tailormap-components/projects/core/src/lib/shared/tests/test-data.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-data.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-manager.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.effects.ts
  tailormap-components/projects/core/src/lib/user-interface/geometry-confirm-buttons/geometry-confirm.service.ts
  tailormap-components/projects/core/src/lib/user-interface/layout.service.ts
  tailormap-components/projects/core/src/lib/user-interface/panel-resizer/panel-resizer.component.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-controller/workflow-controller.service.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/CopyWorkflow.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/NoOpWorkflow.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/SewageWorkflow.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
  tailormap-components/projects/core/tsconfig.spec.json
  tailormap-components/tsconfig.json
Labels: viewer

#2533 16005: Use ngZone.run for detecting CD
  tailormap-components/projects/bridge/src/tailor-map.service.ts
Labels: :bomb: bug, viewer

#2534 16018: Start paspoort with related menu closed
  tailormap-components/projects/core/src/lib/feature-form/state/form.reducer.ts
Labels: enhancement :+1:, viewer

#2537 remove unused ActionBeanContext parameter and other imports
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/security/Authorizations.java
  viewer/src/main/java/nl/b3p/viewer/stripes/ApplicationActionBean.java
Labels: viewer, viewer-config-persistence

#2536 16002: changed share text
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources.properties
Labels: enhancement :+1:, viewer, viewer-admin

#2535 16001: added TM logo for printstylesheet
  viewer/src/main/webapp/WEB-INF/xsl/print/logo.png
Labels: backport v5.8.x, enhancement :+1:, viewer

#2522 16023: Fixes attribute list tab switching
  tailormap-components/projects/core/src/assets/imgs/contextual_drop_top.svg
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-panel/attribute-list-panel.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-panel/attribute-list-panel.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab/attribute-list-tab.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab/attribute-list-tab.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab/attribute-list-tab.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-details-column/attribute-list-details-column.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.actions.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.effects.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.reducer.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.reducer.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.selectors.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/SewageWorkflow.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
Labels: viewer

#2545 Update package after running `npm audit fix`
  tailormap-components/package-lock.json
Labels: viewer

#2547 Improve performance by wrapping create-layer outside ngzone
  tailormap-components/projects/core/src/lib/feature-form/services/edit-feature-geometry.service.ts
  tailormap-components/projects/core/src/lib/shared/highlight-service/highlight.service.ts
Labels: viewer

#2579 15999: dont listen for EDIT_SUCCESS event
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersSnappingController.js
Labels: :bomb: bug, backport v5.6.x, viewer

#2580 15958: only disable save button when the first config is solr type
  viewer/src/main/webapp/viewer-html/components/Search-config.js
Labels: :bomb: bug, backport v5.6.x, viewer, viewer-admin

#2546 16019: Fixes resizing of Attribute list
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-panel/attribute-list-panel.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-panel/attribute-list-panel.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-panel/attribute-list-panel.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list.module.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list/attribute-list.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list/attribute-list.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list/attribute-list.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.actions.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.reducer.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.selectors.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.state.ts
  tailormap-components/projects/core/src/lib/user-interface/layout.service.ts
  tailormap-components/projects/core/src/lib/user-interface/panel-resizer/panel-resizer.component.css
  tailormap-components/projects/core/src/lib/user-interface/panel-resizer/panel-resizer.component.html
  tailormap-components/projects/core/src/lib/user-interface/panel-resizer/panel-resizer.component.ts
  tailormap-components/projects/core/src/styles/styles.css
Labels: viewer

#2582 Form config state
  tailormap-components/projects/core/src/lib/application/models/extended-form-configuration.model.ts
  tailormap-components/projects/core/src/lib/application/state/application.reducer.ts
  tailormap-components/projects/core/src/lib/application/state/application.selectors.ts
  tailormap-components/projects/core/src/lib/application/state/application.state.ts
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.spec.ts
Labels: viewer

#2578 16000: only add layers that are in the selectedcontent
  viewer/src/main/webapp/viewer-html/components/Snapping.js
Labels: :bomb: bug, backport v5.6.x, viewer

#2581 16003: if translate is true dont hide buttons so its possible to rotate/move
  viewer/src/main/webapp/viewer-html/components/ExtendedEdit.js
Labels: :bomb: bug, viewer

#2595 Generic attribute filter
  tailormap-components/projects/core/src/lib/analysis/attribute-selector/attribute-selector.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/attribute-selector/attribute-selector.component.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-mode-thematic/create-layer-mode-thematic.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria-description/criteria-description.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.css
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.html
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/helpers/criteria.helper.ts
  tailormap-components/projects/core/src/lib/analysis/helpers/style.helper.spec.ts
  tailormap-components/projects/core/src/lib/analysis/helpers/style.helper.ts
  tailormap-components/projects/core/src/lib/analysis/helpers/test-data/style-test-data.ts
  tailormap-components/projects/core/src/lib/analysis/models/analysis-source.model.ts
  tailormap-components/projects/core/src/lib/analysis/models/criteria-condition-type.model.ts
  tailormap-components/projects/core/src/lib/analysis/models/criteria-condition.model.ts
  tailormap-components/projects/core/src/lib/analysis/models/scoped-user-layer-style.model.ts
  tailormap-components/projects/core/src/lib/analysis/state/test-data/analysis-test-data.ts
  tailormap-components/projects/core/src/lib/analysis/style-form/style-form.component.ts
  tailormap-components/projects/core/src/lib/analysis/style-preview/style-preview.component.spec.ts
  tailormap-components/projects/core/src/lib/application/helpers/attribute-type.helper.ts
  tailormap-components/projects/core/src/lib/application/services/mocks/metadata.service.mock.ts
  tailormap-components/projects/core/src/lib/shared/attribute-filter/attribute-filter.component.css
  tailormap-components/projects/core/src/lib/shared/attribute-filter/attribute-filter.component.html
  tailormap-components/projects/core/src/lib/shared/attribute-filter/attribute-filter.component.spec.ts
  tailormap-components/projects/core/src/lib/shared/attribute-filter/attribute-filter.component.ts
  tailormap-components/projects/core/src/lib/shared/helpers/attribute-filter.helper.ts
  tailormap-components/projects/core/src/lib/shared/models/attribute-filter-type.model.ts
  tailormap-components/projects/core/src/lib/shared/models/attribute-filter.model.ts
  tailormap-components/projects/core/src/lib/shared/models/attribute-type.enum.ts
  tailormap-components/projects/core/src/lib/shared/shared.module.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-filter/attribute-list-filter.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-filter/attribute-list-filter.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-filter/attribute-list-filter.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/helpers/attribute-list-filter.helper.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/models/attribute-list-column-models.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/models/attribute-list-feature-type-data.model.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/models/attribute-list-filter-models.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.actions.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.reducer.ts
Labels: viewer

#2589 Use tailormap filters in attribute list
  tailormap-components/projects/bridge/src/tailor-map.service.mock.ts
  tailormap-components/projects/bridge/src/tailor-map.service.ts
  tailormap-components/projects/bridge/typings/Components.d.ts
  tailormap-components/projects/bridge/typings/Mapcomponents.d.ts
  tailormap-components/projects/core/src/lib/application/services/application.service.ts
  tailormap-components/projects/core/src/lib/shared/tests/test-data.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/helpers/attribute-list-filter.helper.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-data.service.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-data.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.effects.ts
  viewer/src/main/webapp/viewer-html/common/CQLFilterWrapper.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
Labels: viewer

#2594 [mantis-16036] prevent NPE when a misconfigured simplefilter is present
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
Labels: :bomb: bug, backport v5.6.x, backport v5.8.x, viewer

#2593 15994: Copy Component: Use seperate state + layout fixes
  tailormap-components/projects/core/src/lib/feature-form/feature-form.module.ts
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.spec.ts
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.html
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.actions.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.reducer.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.selectors.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.state.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-controller/workflow-controller.component.html
  tailormap-components/projects/core/src/lib/workflow/workflow-controller/workflow-controller.component.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/CopyWorkflow.ts
  tailormap-components/projects/core/src/styles/styles.css
Labels: viewer

#2600 Gebruik Java 11 database drivers
  .github/workflows/codeql-analysis.yml
  codecov.yml
  pom.xml
  tomcat-lib/README.md
  tomcat-lib/pom.xml
  viewer-admin/pom.xml
  viewer/pom.xml
Labels: build infrastructure, java11, no backport :no_entry:, viewer, viewer-admin

#2606 set restriction to attribute, and load infocomponents after all compo…
  viewer/src/main/webapp/viewer-html/components/FeatureReport.js
Labels: backport v5.6.x, backport v5.8.x, viewer

#2611 16502: copy mainFeatures objects from parentFeature
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2613 16005: layer is allready the ID string
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
Labels: :bomb: bug, backport v5.8.x, viewer

#2612 15887: clear formsForNew for new object in pasport
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2614 16057 & 16056: Bug fix/16057/16056 draw action keeps active
  tailormap-components/projects/core/src/lib/workflow/state/workflow.reducer.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2622 16048: Edit feature geometry
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.html
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.reducer.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.selectors.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.state-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.state.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-controller/workflow-controller.component.ts
  tailormap-components/projects/core/src/styles/styles.css
Labels: :bomb: bug, backport v5.8.x, viewer

#2619 16047: is layer is userLayer use orginal-layer-name
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2621 Attribute list fixes
  tailormap-components/projects/core/src/lib/shared/helpers/attribute-filter.helper.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-data.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-manager.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.actions.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.effects.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.reducer.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.reducer.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2624 TM-27: Get all the unique values when creating thematic layer
  tailormap-components/projects/core/src/lib/analysis/services/create-style.service.ts
  tailormap-components/projects/core/src/lib/application/services/metadata.service.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2628 TM-28: Show empty form for bulk edit
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2620 check if the value was indeed in the list of options. if not, use the…
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2631 TM-26: first check config.fields if it holds the formfield to show
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2632 TM-36: Show message when creating layer without query
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2637 [backport v5.8.x] Bump actions/cache from v2.1.4 to v2.1.5 (#2636), Bump easingthemes/ssh-deploy from v2.1.6 to v2.1.7 (#2635)
  .github/workflows/angular-components-deployment.yml
  .github/workflows/angular-components.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/macos-maven.yml
  .github/workflows/ubuntu-maven.yml
Labels: build infrastructure

#2642 TM-56: deleted filter check. This check hold values from previuos feature if…
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2643 Tm-32: added option to filter on NULL values
  tailormap-components/projects/core/src/lib/analysis/criteria/helpers/criteria.helper.ts
  tailormap-components/projects/core/src/lib/shared/attribute-filter/attribute-filter.component.ts
  tailormap-components/projects/core/src/lib/shared/helpers/attribute-filter.helper.ts
  tailormap-components/projects/core/src/lib/shared/models/attribute-type.enum.ts
Labels: backport v5.8.x, enhancement :+1:, viewer

#2641 Tm-33: After selected content changed add layers to the map
  viewer/src/main/webapp/viewer-html/components/GBI.js
Labels: :bomb: bug, backport v5.8.x, viewer

#2648 Bug/tm 21 add relates to userlayer
  viewer/src/main/java/nl/b3p/viewer/stripes/AttributesActionBean.java
  viewer/src/main/java/nl/b3p/viewer/userlayer/TailormapDBManager.java
  viewer/src/main/java/nl/b3p/viewer/util/FlamingoCQL.java
Labels: backport v5.8.x, viewer

#2644 TM-35: Show message for creating userlayer from userlayer, this is not valid
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2653 add geometrycolumsn for imbor tables
  tailormap-components/projects/core/src/lib/shared/feature-initializer/feature-initializer.service.ts
Labels: backport v5.8.x, viewer

#2655 TM-64: Refresh attribute list after editing user layer features
  tailormap-components/projects/core/src/lib/application/state/application.actions.ts
  tailormap-components/projects/core/src/lib/application/state/application.reducer.ts
  tailormap-components/projects/core/src/lib/application/state/application.selectors.ts
  tailormap-components/projects/core/src/lib/application/state/application.state.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.effects.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.effects.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2658 add parentheses around filter to fix filter retrieval
  viewer/src/main/java/nl/b3p/viewer/stripes/AttributesActionBean.java
Labels: backport v5.8.x, viewer

#2657 [v5.8.x] controleer in alle modules of er java 8 classfiles worden geproduceerd
  .github/workflows/ubuntu-maven.yml
  .jenkins/check-java-binary-version.sh
  Jenkinsfile
Labels: :bomb: bug, build infrastructure, no backport :no_entry:

#2661 Add view to gt_pk_metadata
  viewer/src/main/java/nl/b3p/viewer/userlayer/DataBase.java
  viewer/src/main/java/nl/b3p/viewer/userlayer/Oracle.java
  viewer/src/main/java/nl/b3p/viewer/userlayer/PostgreSQL.java
  viewer/src/main/java/nl/b3p/viewer/userlayer/SQLServer.java
Labels: backport v5.8.x, viewer

#2662 TM-11: use css variable for multiple columns in passport
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.css
  tailormap-components/projects/core/src/lib/feature-form/form/form-models.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.css
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.html
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/styles/styles.css
Labels: enhancement :+1:, viewer

#2671 TM-66: Allow for deeper nested relations in the attribute list
  tailormap-components/projects/core/src/lib/shared/util/map.helper.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-column-selection/attribute-list-column-selection.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-content/attribute-list-content.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-details/attribute-list-details.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list/attribute-list.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/helpers/FILTERS_README.txt
  tailormap-components/projects/core/src/lib/user-interface/attributelist/helpers/attribute-list-filter.helper.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/helpers/update-attribute-list-state.helper.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/models/attribute-list-feature-type-data.model.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/models/attribute-list-tab.model.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-data.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-export.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-manager.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.actions.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.effects.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.reducer.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.reducer.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.selectors.ts
Labels: viewer
