Repository B3Partners/tailormap, pull requests merged in 2021-12, with the labels that each got.

#2981 GBIM-17: Resizable attribute list columns
  tailormap-components/package-lock.json
  tailormap-components/package.json
Labels: viewer

#2982 GBIM-250: Changed label for copying features
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.html
Labels: viewer

#2995 Dependency updates v5.8.x
  pom.xml
Labels: dependencies

#2994 Dependency updates
  pom.xml
Labels: dependencies

#2997 Bump jackson2.version from 2.12.5 to 2.12.6
  pom.xml
Labels: dependencies

#3007 Bump dependency-check-maven from 6.3.1 to 6.5.1
  pom.xml
Labels: build infrastructure

#2983 GBIM-183: bulk edit from attributelist
  tailormap-components/projects/core/src/lib/feature-form/form-actions/form-actions.service.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/shared/generated/services/feature-controller.service.ts
Labels: enhancement, viewer

#3017 [TM-353] Bump GeoTools from 25.3 to 25.4
  pom.xml
  viewer-admin/src/main/java/nl/b3p/viewer/admin/stripes/ChooseApplicationActionBean.java
  viewer/src/main/java/nl/b3p/viewer/features/ShapeDownloader.java
  viewer/src/main/java/nl/b3p/viewer/stripes/ApplicationActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/I18nActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/LocalizableApplicationActionBean.java
  viewer/src/main/java/nl/b3p/viewer/stripes/PrintActionBean.java
  viewer/src/main/java/nl/b3p/viewer/util/FlamingoCQL.java
Labels: security, dependencies, viewer-admin, viewer

#3019 Revert "Bump cargo-maven3-plugin from 1.9.8 to 1.9.9"
  pom.xml
Labels: build infrastructure
