Repository B3Partners/tailormap, pull requests merged in 2021-09, with the labels that each got.

#2886 Bugfixes
  tailormap-components/projects/core/src/lib/application/helpers/attribute-type.helper.ts
  tailormap-components/projects/core/src/lib/application/state/application.selectors.ts
  tailormap-components/projects/core/src/lib/feature-form/form-attribute-list-button/form-attribute-list-button.component.ts
  tailormap-components/projects/core/src/lib/shared/attribute-service/attribute-models.ts
  tailormap-components/projects/core/src/lib/shared/feature-selection/feature-selection.service.ts
  tailormap-components/projects/core/src/lib/shared/layer-utils/layer-utils.service.ts
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/add-feature-menu/add-feature-menu.component.html
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/add-feature-menu/add-feature-menu.component.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
Labels: viewer

#2892 Fix/showing fonts for angular
  tailormap-components/angular.json
  viewer-admin/pom.xml
  viewer/pom.xml
Labels: viewer-admin, viewer

#2896 Form-editor changes
  tailormap-components-config/src/app/app.module.ts
  viewer-admin/src/main/java/nl/tailormap/viewer/admin/stripes/FormActionBean.java
  viewer-admin/src/main/webapp/WEB-INF/jsp/services/formAngular.jsp
Labels: viewer-admin

#2897 Save string value instead of ID when saving field with linked list
  tailormap-components/projects/core/src/lib/feature-form/form-field/form-field-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form-models.ts
  tailormap-components/projects/core/src/lib/feature-form/linked-fields/domain-repository/domain-repository.service.ts
  tailormap-components/projects/core/src/lib/shared/formconfig-repository/form-config-repository.service.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/input-field/input-field.component.html
  tailormap-components/projects/core/src/lib/user-interface/generic-components/input-field/input-field.component.ts
Labels: viewer

#2898 Readonly fields in passport
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-field/form-field-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form-models.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/checkbox-field/checkbox-field.component.css
  tailormap-components/projects/core/src/lib/user-interface/generic-components/checkbox-field/checkbox-field.component.html
  tailormap-components/projects/core/src/lib/user-interface/generic-components/checkbox-field/checkbox-field.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/checkbox-field/checkbox-field.component.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/input-field/input-field.component.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/label-field/label-field.component.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/select-field/select-field.component.css
  tailormap-components/projects/core/src/lib/user-interface/generic-components/select-field/select-field.component.html
  tailormap-components/projects/core/src/lib/user-interface/generic-components/select-field/select-field.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/select-field/select-field.component.ts
  tailormap-components/projects/core/src/lib/user-interface/user-interface.module.ts
Labels: build infrastructure, viewer

#2902 Create feature for deeper relations on form
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-node/form-node.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-node/form-node.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.html
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.spec.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.reducer.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.state-helpers.ts
Labels: viewer

#2904 Attributelist fixes
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/bridge/typings/Mapcomponents.d.ts
  tailormap-components/projects/core/src/lib/analysis/analysis.module.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria-description/criteria-description.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/helpers/criteria.helper.ts
  tailormap-components/projects/core/src/lib/application/application-tree-node/application-tree-node.component.css
  tailormap-components/projects/core/src/lib/application/application-tree-node/application-tree-node.component.html
  tailormap-components/projects/core/src/lib/application/application-tree-node/application-tree-node.component.spec.ts
  tailormap-components/projects/core/src/lib/application/application-tree-node/application-tree-node.component.ts
  tailormap-components/projects/core/src/lib/application/application.module.ts
  tailormap-components/projects/core/src/lib/feature-form/feature-form.module.ts
  tailormap-components/projects/core/src/lib/feature-form/form-attribute-list-button/form-attribute-list-button.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
  tailormap-components/projects/core/src/lib/feature-form/services/form-attribute-list.service.spec.ts
  tailormap-components/projects/core/src/lib/feature-form/services/form-attribute-list.service.ts
  tailormap-components/projects/core/src/lib/shared/attribute-filter/attribute-filter.component.css
  tailormap-components/projects/core/src/lib/shared/attribute-filter/attribute-filter.component.html
  tailormap-components/projects/core/src/lib/shared/attribute-filter/attribute-filter.component.spec.ts
  tailormap-components/projects/core/src/lib/shared/attribute-filter/attribute-filter.component.ts
  tailormap-components/projects/core/src/lib/shared/generated/services/feature-controller.service.ts
  tailormap-components/projects/core/src/lib/shared/helpers/attribute-filter.helper.ts
  tailormap-components/projects/core/src/lib/shared/shared.module.ts
  viewer-config-persistence/src/main/java/nl/tailormap/viewer/config/app/ApplicationLayer.java
  viewer-config-persistence/src/main/java/nl/tailormap/viewer/config/services/Layer.java
  viewer-helpers/src/main/java/nl/tailormap/viewer/helpers/app/ApplicationLayerHelper.java
  viewer/src/main/java/nl/tailormap/viewer/userlayer/TailormapDBManager.java
Labels: viewer, viewer-config-persistence

#2907 Update core-components
  tailormap-components/package-lock.json
  tailormap-components/package.json
Labels: viewer
