Repository B3Partners/tailormap, pull requests merged in 2021-10, with the labels that each got.

#2908 Use POST to get features by ID
  tailormap-components/projects/core/src/lib/feature-form/services/form-attribute-list.service.ts
  tailormap-components/projects/core/src/lib/shared/generated/services/feature-controller.service.ts
Labels: viewer

#2909 Get the feature from a user layer after clicking the map
  tailormap-components/projects/core/src/lib/feature-form/form-attribute-list-button/form-attribute-list-button.component.ts
  tailormap-components/projects/core/src/lib/shared/feature-selection/feature-selection.helper.ts
  tailormap-components/projects/core/src/lib/shared/feature-selection/feature-selection.service.ts
  tailormap-components/projects/core/src/lib/shared/layer-utils/layer-utils.service.spec.ts
  tailormap-components/projects/core/src/lib/shared/layer-utils/layer-utils.service.ts
Labels: viewer

#2910 Userlayer creation UI improvements
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.ts
  tailormap-components/projects/core/src/lib/application/services/metadata.service.ts
  tailormap-components/projects/core/src/lib/feature-form/services/form-attribute-list.service.spec.ts
  tailormap-components/projects/core/src/lib/feature-form/services/form-attribute-list.service.ts
  tailormap-components/projects/core/src/lib/shared/feature-selection/feature-selection.service.ts
Labels: viewer

#2912 delete bug.js; grappig, maar less is more en dit is onzin om bij te houden
  viewer-admin/src/main/webapp/WEB-INF/jsp/index.jsp
  viewer-admin/src/main/webapp/resources/images/fly-sprite.png
  viewer-admin/src/main/webapp/resources/images/spider-sprite (copy).png
  viewer-admin/src/main/webapp/resources/images/spider-sprite.png
  viewer-admin/src/main/webapp/resources/js/bug-min.js
  viewer-admin/src/main/webapp/resources/js/bug.js
Labels: hacktoberfest, hacktoberfest-accepted, viewer-admin

#2914 Trigger editFeaturesComplete after editing feature in passport
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/core/src/lib/feature-form/state/form.effects.ts
Labels: hacktoberfest, hacktoberfest-accepted, viewer
