Repository B3Partners/tailormap, pull requests merged in 2021-03, with the labels that each got.

#2397 15892: Save feature after geometry edit
  tailormap-components/projects/bridge/typings/Components.d.ts
  tailormap-components/projects/bridge/typings/Mapcomponents.d.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.spec.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/services/edit-feature-geometry.service.spec.ts
  tailormap-components/projects/core/src/lib/feature-form/services/edit-feature-geometry.service.ts
  tailormap-components/projects/core/src/lib/feature-form/services/mocks/edit-feature-geometry.service.mock.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.actions.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.reducer.ts
  tailormap-components/projects/core/src/lib/shared/feature-initializer/feature-initializer.service.ts
  tailormap-components/projects/core/src/lib/shared/tests/test-data.ts
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/edit-bar/edit-bar.component.ts
  tailormap-components/projects/core/src/lib/user-interface/geometry-confirm-buttons/geometry-confirm.service.ts
  tailormap-components/projects/core/src/lib/workflow/state/workflow-models.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-controller/workflow-controller.component.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-factory/workflow-factory.service.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/EditgeometryWorkflow.spec.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/EditgeometryWorkflow.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
Labels: backport v5.8.x, viewer

#2424 15897: Improved help message for statistic functions
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-checkbox-column/attribute-list-checkbox-column.component.ts
Labels: viewer

#2411 15887: object list too long in form component
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
Labels: viewer

#2426 15907: Use flat CSS generation mode for user layer styles
  tailormap-components/projects/core/src/lib/analysis/helpers/style.helper.spec.ts
  tailormap-components/projects/core/src/lib/analysis/helpers/style.helper.ts
Labels: viewer

#2399 15875: Apply Attribute List configuration
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-button/attribute-list-button.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-button/attribute-list-button.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-panel/attribute-list-panel.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-panel/attribute-list-panel.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/models/attribute-list.config.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.state.ts
  viewer/src/main/webapp/viewer-html/components/NgAttributeList-config.js
  viewer/src/main/webapp/viewer-html/components/NgAttributeList.js
Labels: backport v5.8.x, viewer

#2410 update libs, and configure dependabot to only report updates to depen…
  .github/dependabot.yml
  tailormap-components/package-lock.json
  tailormap-components/package.json
Labels: build infrastructure, dependencies, viewer

#2391 sanitize parameter input to prevent xss injection. Closes #2390
  pom.xml
  viewer/pom.xml
  viewer/src/main/java/nl/b3p/viewer/stripes/BookmarkActionBean.java
Labels: backport v5.6.x, backport v5.8.x, security, viewer

#2425 15900: Improve look and feel of edit bar
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/add-feature-menu/add-feature-menu.component.css
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/add-feature-menu/add-feature-menu.component.html
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/add-feature-menu/add-feature-menu.component.ts
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/add-feature-menu/menu-button/menu-button.component.css
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/add-feature-menu/menu-button/menu-button.component.html
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/edit-bar/edit-bar.component.css
  tailormap-components/projects/core/src/styles/styles.css
Labels: viewer

#2396 15893: remove items gives error
  tailormap-components/projects/core/src/lib/feature-form/form-actions/form-actions.service.ts
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.actions.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.reducer.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.state-helpers.ts
  viewer/src/main/java/nl/b3p/viewer/stripes/ProxyRESTActionBean.java
Labels: viewer

#2395 15929: add new items to tree
  tailormap-components/projects/core/src/lib/feature-form/state/form.state-helpers.ts
Labels: viewer

#2398 15886: Allow feature selection before editing
  tailormap-components/projects/core/src/lib/shared/feature-selection/feature-selection.component.css
  tailormap-components/projects/core/src/lib/shared/feature-selection/feature-selection.component.html
  tailormap-components/projects/core/src/lib/shared/feature-selection/feature-selection.component.spec.ts
  tailormap-components/projects/core/src/lib/shared/feature-selection/feature-selection.component.ts
  tailormap-components/projects/core/src/lib/shared/shared.module.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
  tailormap-components/projects/core/src/styles/custom-theme.scss
Labels: backport v5.8.x, viewer

#2445 Java 8 classfiles als compiler output voor v5.8.x
  .jenkins/check-java-binary-version.sh
  Jenkinsfile
  pom.xml
Labels: build infrastructure, viewer

#2386 Verwijder componenten die niet in de stable branch moeten zitten
  viewer-admin/src/main/webapp/WEB-INF/web.xml
  viewer/src/main/webapp/viewer-html/components/components.json
Labels: build infrastructure, featurerequest :+1:, no backport :no_entry:, viewer, viewer-admin

#2437 15915: if statement was wrong
  viewer/src/main/webapp/viewer-html/components/StreetView.js
Labels: :bomb: bug, backport v5.6.x, backport v5.8.x, viewer

#2441 [Backport v5.6.x] sanitize parameter input to prevent xss injection.
  pom.xml
  viewer/pom.xml
  viewer/src/main/java/nl/b3p/viewer/stripes/BookmarkActionBean.java
Labels: security, viewer

#2436 15884: set scale higher when its lower than 1
  viewer/src/main/webapp/viewer-html/components/GBI.js
Labels: backport v5.8.x, viewer

#2449 15935: Fixed always active bug for simple drawing + fixed some layout issues
  viewer/src/main/webapp/viewer-html/common/ScreenPopup.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersVectorLayer.js
  viewer/src/main/webapp/viewer-html/components/Drawing-config.js
  viewer/src/main/webapp/viewer-html/components/Drawing.js
  viewer/src/main/webapp/viewer-html/components/components.json
Labels: :bomb: bug, backport v5.6.x, backport v5.8.x, viewer

#2464 [mantis-15968] don't set focus on first field before editing
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: backport v5.8.x, enhancement :+1:, viewer

#2463 15901: better message for column length too long and suggest alternative
  viewer/src/main/java/nl/b3p/viewer/stripes/DownloadFeaturesActionBean.java
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en.properties
Labels: backport v5.6.x, backport v5.8.x, enhancement :+1:, viewer

#2468 15970: added close handler on featuresGrid window
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: :bomb: bug, backport v5.6.x, backport v5.8.x, viewer

#2473 15976: Fixes creating criteria for sources without relations
  tailormap-components/projects/core/src/lib/application/services/metadata.service.ts
Labels: backport v5.8.x, viewer

#2477 15973: Renamed 'criteria' to 'criterium'
  tailormap-components/projects/core/src/lib/analysis/criteria/advanced-criteria/advanced-criteria.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria-group/criteria-group.component.html
Labels: backport v5.8.x, viewer

#2476 15974: Show passport fields / columns for user layers in attribute list
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-manager.service.ts
Labels: backport v5.8.x, viewer

#2474 15897: Improved Statistics workflow
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-checkbox-column/attribute-list-checkbox-column.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-statistics-menu/attribute-list-statistics-menu.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-statistic-models.ts
Labels: backport v5.8.x, viewer

#2475 Fixes style colors
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-statistics-menu/attribute-list-statistics-menu.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.css
  tailormap-components/projects/core/src/styles/custom-theme.scss
Labels: backport v5.8.x, viewer

#2483 15915: Delete marker when tool is activated is userMarker is true
  viewer/src/main/webapp/viewer-html/components/StreetView.js
Labels: :bomb: bug, backport v5.6.x, backport v5.8.x, viewer

#2486 15886: Allow (de)selection of layers to enable 'sateprikker' / single…
  tailormap-components/projects/bridge/src/tailor-map.service.ts
  tailormap-components/projects/core/src/lib/application/services/application.service.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
  tailormap-components/projects/core/src/styles/styles.css
  viewer/src/main/webapp/viewer-html/components/TOC.js
Labels: backport v5.8.x, enhancement :+1:, viewer

#2491 15881: sanitize layername
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2490 15891: use compareable value in formcontrols; register on formgroup in creat…
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2492 15876: open paspoort form in editmode after drawing feature
  tailormap-components/projects/core/src/lib/feature-form/state/form.actions.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.reducer.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2493 15887: fill formsNew based on relates that has been set in the viewer-admin
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2494 [Backport v5.8.x] 15886: Allow (de)selection of layers to enable 'sateprikker' / single…
  tailormap-components/projects/bridge/src/tailor-map.service.ts
  tailormap-components/projects/core/src/lib/application/services/application.service.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
  tailormap-components/projects/core/src/styles/styles.css
  viewer/src/main/webapp/viewer-html/components/TOC.js
Labels: :bomb: bug, viewer

#2500 [Backport v5.8.x] 15876: open paspoort form in editmode after drawing feature
  tailormap-components/projects/core/src/lib/feature-form/state/form.actions.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.reducer.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
Labels: viewer

#2501 tslintfix maximun line length
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
Labels: :bomb: bug, backport v5.8.x, viewer

#2495 15739: check if there is an serviceLayer for all appLayers
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
Labels: :bomb: bug, backport v5.6.x, backport v5.8.x, viewer

#2472 Save Form config as array instead of Map inside state
  tailormap-components/projects/core/src/lib/application/services/application.service.ts
  tailormap-components/projects/core/src/lib/application/state/application.reducer.ts
  tailormap-components/projects/core/src/lib/application/state/application.selectors.ts
  tailormap-components/projects/core/src/lib/application/state/application.state.ts
  tailormap-components/projects/core/src/lib/application/state/test-data/application-test-data.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/linked-fields/domain-repository/domain-repository.service.ts
Labels: viewer

#2453 Analysis: Show the object count inside the description of a query (at…
  tailormap-components/projects/core/src/lib/analysis/create-layer-mode-attributes/create-layer-mode-attributes.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-styling/create-layer-styling.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria-description/criteria-description.component.css
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria-description/criteria-description.component.html
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria-description/criteria-description.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria-description/criteria-description.component.ts
Labels: backport v5.8.x, viewer

#2516 Added attribute relations to relation, so the tree of relations is al…
  tailormap-components/projects/core/src/lib/shared/attribute-service/attribute-models.ts
Labels: enhancement :+1:, featurerequest :+1:, viewer

#2496 Upgrade GeoTools van 24.x naar 25.x
  pom.xml
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcgis/ArcGISDataStore.java
  viewer-commons/src/main/java/nl/b3p/geotools/data/arcgis/ArcGISDataStoreFactory.java
Labels: GeoTools, backport v5.8.x, dependencies

#2471 Add hyperlink form field type in passport
  tailormap-components/projects/core/src/lib/application/style/application-tree.css
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.spec.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form-models.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.css
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.html
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.actions.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.reducer.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.selectors.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.state.ts
  tailormap-components/projects/core/src/lib/shared/attribute-service/attribute-models.ts
  tailormap-components/projects/core/src/lib/shared/feature-selection/feature-selection.component.spec.ts
  tailormap-components/projects/core/src/lib/shared/tree/tree.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-table/attribute-list-table.component.html
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/edit-bar/edit-bar.component.html
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/edit-bar/edit-bar.component.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/base-field/base-field.component.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/input-field/input-field.component.css
  tailormap-components/projects/core/src/lib/user-interface/generic-components/input-field/input-field.component.html
  tailormap-components/projects/core/src/lib/user-interface/generic-components/input-field/input-field.component.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/label-field/label-field.component.css
  tailormap-components/projects/core/src/lib/user-interface/generic-components/label-field/label-field.component.html
  tailormap-components/projects/core/src/lib/workflow/workflows/CopyWorkflow.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/NoOpWorkflow.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/SewageWorkflow.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/Workflow.ts
  tailormap-components/projects/core/src/styles/styles.css
Labels: backport v5.8.x, viewer

#2507 Attribute list reducer tests
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/attribute-list.reducer.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/state/mocks/attribute-list-test-data.ts
Labels: backport v5.8.x, viewer

#2524 16014: Adds configuration for max features + download params
  tailormap-components/projects/core/src/lib/user-interface/attributelist/models/attribute-list.config.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/services/attribute-list-export.service.ts
  viewer/src/main/webapp/viewer-html/components/NgAttributeList-config.js
  viewer/src/main/webapp/viewer-html/components/NgAttributeList.js
Labels: :bomb: bug, backport v5.8.x, viewer

#2523 [mantis-16017] Fixes bulk edit
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.ts
Labels: :bomb: bug, viewer
