Repository B3Partners/tailormap, pull requests merged in 2021-01, with the labels that each got.

#2194 Feat/gbiw 316 create userlayer from attributelist
  tailormap-components/projects/bridge/typings/Mapcomponents.d.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-mode-attributes/create-layer-mode-attributes.component.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-mode-thematic/create-layer-mode-thematic.component.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-styling/create-layer-styling.component.ts
  tailormap-components/projects/core/src/lib/analysis/services/user-layer.service.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.effects.ts
  tailormap-components/projects/core/src/lib/application/state/application.effects.ts
  tailormap-components/projects/core/src/lib/shared/value-service/value.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-filter.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-filter-values-form/attributelist-filter-values-form.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-layername-chooser/attributelist-layername-chooser.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-layername-chooser/attributelist-layername-chooser.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-layername-chooser/attributelist-layername-chooser.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-layername-chooser/attributelist-layername-chooser.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tab-toolbar/attributelist-tab-toolbar.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tab-toolbar/attributelist-tab-toolbar.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tab-toolbar/attributelist-tab-toolbar.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist.module.ts
Labels: viewer

#2199 Create user layer from attribute list improvements
  tailormap-components/projects/core/src/lib/analysis/create-layer-layer-selection/create-layer-layer-selection.component.ts
  tailormap-components/projects/core/src/lib/analysis/helpers/user-layer.helper.ts
  tailormap-components/projects/core/src/lib/analysis/services/user-layer.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tab-toolbar/attributelist-tab-toolbar.component.ts
Labels: viewer

#2201 Feat/attributelist tree filters
  tailormap-components/projects/core/src/lib/shared/attribute-service/attribute-models.ts
  tailormap-components/projects/core/src/lib/shared/attribute-service/attribute.service.ts
  tailormap-components/projects/core/src/lib/shared/generated/models/feature.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-column-controller.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-datasource.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-filter.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-table/attributelist-table.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tree/attributelist-tree-models.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tree/attributelist-tree.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tree/attributelist-tree.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tree/attributelist-tree.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tree/attributelist-tree.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist.module.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist.service.ts
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/FeatureSource.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/FeatureTypeRelation.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/FeatureTypeRelationKey.java
  viewer/src/main/java/nl/b3p/viewer/stripes/UserLayerActionBean.java
  viewer/src/main/java/nl/b3p/viewer/userlayer/TMFilterToSQL.java
  viewer/src/main/java/nl/b3p/viewer/userlayer/UserLayerHandler.java
  viewer/src/main/java/nl/b3p/viewer/util/FlamingoCQL.java
  viewer/src/main/java/nl/b3p/viewer/util/Subselect.java
Labels: viewer, viewer-config-persistence

#2187 Feat/gbiw 313 related filter
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/helpers/criteria.helper.ts
  tailormap-components/projects/core/src/lib/analysis/models/criteria-condition.model.ts
  tailormap-components/projects/core/src/lib/analysis/services/user-layer.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-datasource.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-filter.ts
  viewer-config-persistence/src/test/resources/nl/b3p/viewer/util/testdata.sql
  viewer/src/main/java/nl/b3p/viewer/userlayer/TMFilterToSQL.java
  viewer/src/main/java/nl/b3p/viewer/userlayer/UserLayerHandler.java
  viewer/src/main/java/nl/b3p/viewer/util/FlamingoCQL.java
  viewer/src/test/java/nl/b3p/viewer/userlayer/PostgreSQLIntegrationTest.java
  viewer/src/test/java/nl/b3p/viewer/util/FlamingoCQLTest.java
Labels: viewer, viewer-config-persistence

#2204 sanitize passport
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-datasource.ts
Labels: viewer

#2205 Hide create layer button in attributelist when the layer is already a…
  tailormap-components/projects/core/src/lib/analysis/services/user-layer.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tab-toolbar/attributelist-tab-toolbar.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tab-toolbar/attributelist-tab-toolbar.component.ts
Labels: viewer

#2217 Added tests for layerservice. Query userlayers with ul_LAYERID, so th…
  tailormap-components/projects/bridge/src/tailor-map.service.mock.ts
  tailormap-components/projects/bridge/typings/Mapcomponents.d.ts
  tailormap-components/projects/core/src/lib/shared/layer-utils/layer-utils.service.spec.ts
  tailormap-components/projects/core/src/lib/shared/layer-utils/layer-utils.service.ts
  tailormap-components/projects/core/src/lib/shared/tests/test-data.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-factory/workflow-factory.service.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/Workflow.ts
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/app/ApplicationLayer.java
Labels: :bomb: bug, viewer, viewer-config-persistence

#2215 GBIW-324: Show scale selector
  tailormap-components/projects/bridge/typings/Mapcomponents.d.ts
  tailormap-components/projects/core/src/lib/analysis/analysis.module.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-mode-attributes/create-layer-mode-attributes.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-styling/create-layer-styling.component.html
  tailormap-components/projects/core/src/lib/analysis/create-layer-styling/create-layer-styling.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/advanced-criteria/advanced-criteria.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/simple-criteria/simple-criteria.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/helpers/style.helper.spec.ts
  tailormap-components/projects/core/src/lib/analysis/helpers/style.helper.ts
  tailormap-components/projects/core/src/lib/analysis/models/user-layer-style.model.ts
  tailormap-components/projects/core/src/lib/analysis/resolution-selector/resolution-selector.component.css
  tailormap-components/projects/core/src/lib/analysis/resolution-selector/resolution-selector.component.html
  tailormap-components/projects/core/src/lib/analysis/resolution-selector/resolution-selector.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/resolution-selector/resolution-selector.component.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.actions.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.reducer.spec.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.reducer.ts
  tailormap-components/projects/core/src/lib/analysis/style-form/style-form.component.html
  tailormap-components/projects/core/src/lib/analysis/style-form/style-form.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/style-form/style-form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.spec.ts
  tailormap-components/projects/core/src/lib/shared/shared.module.ts
  tailormap-components/projects/core/src/lib/shared/tests/test-data.ts
  tailormap-components/projects/core/src/lib/shared/util/color.ts
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/add-feature-menu/add-feature-menu.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/add-feature-menu/menu-button/menu-button.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/edit-bar/edit-bar.component.spec.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-controller/workflow-controller.component.spec.ts
Labels: viewer

#2218 Stop rendering when Attributelist is not active
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-panel/attributelist-panel.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-panel/attributelist-panel.component.ts
Labels: viewer

#2214 Fix saving new geometries
  tailormap-components/projects/core/src/lib/shared/tests/test-data.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/EditgeometryWorkflow.spec.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/EditgeometryWorkflow.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/mocks/workflow.mock.ts
Labels: viewer

#2224 Add label to legend + Show legend preview when creating style
  tailormap-components/projects/core/src/assets/imgs/markers/arrow.svg
  tailormap-components/projects/core/src/assets/imgs/markers/circle.svg
  tailormap-components/projects/core/src/assets/imgs/markers/cross.svg
  tailormap-components/projects/core/src/assets/imgs/markers/square.svg
  tailormap-components/projects/core/src/assets/imgs/markers/star.svg
  tailormap-components/projects/core/src/assets/imgs/markers/triangle.svg
  tailormap-components/projects/core/src/assets/imgs/markers/x.svg
  tailormap-components/projects/core/src/lib/analysis/analysis.module.ts
  tailormap-components/projects/core/src/lib/analysis/attribute-selector/attribute-selector.component.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-form/create-layer-form.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-mode-attributes/create-layer-mode-attributes.component.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-mode-thematic/create-layer-mode-thematic.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-mode-thematic/create-layer-mode-thematic.component.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-panel/create-layer-panel.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-panel/create-layer-panel.component.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-styling/create-layer-styling.component.css
  tailormap-components/projects/core/src/lib/analysis/create-layer-styling/create-layer-styling.component.html
  tailormap-components/projects/core/src/lib/analysis/create-layer-styling/create-layer-styling.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.ts
  tailormap-components/projects/core/src/lib/analysis/helpers/style.helper.spec.ts
  tailormap-components/projects/core/src/lib/analysis/helpers/style.helper.ts
  tailormap-components/projects/core/src/lib/analysis/helpers/test-data/style-test-data.ts
  tailormap-components/projects/core/src/lib/analysis/models/user-layer-style.model.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.actions.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.effects.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.reducer.ts
  tailormap-components/projects/core/src/lib/analysis/state/test-data/analysis-test-data.ts
  tailormap-components/projects/core/src/lib/analysis/style-form/style-form.component.html
  tailormap-components/projects/core/src/lib/analysis/style-form/style-form.component.ts
  tailormap-components/projects/core/src/lib/analysis/style-preview/style-preview.component.css
  tailormap-components/projects/core/src/lib/analysis/style-preview/style-preview.component.html
  tailormap-components/projects/core/src/lib/analysis/style-preview/style-preview.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/style-preview/style-preview.component.ts
  tailormap-components/projects/core/src/lib/shared/color-picker/color-picker.component.ts
  tailormap-components/projects/core/src/lib/shared/icon-picker/icon-picker.component.html
  tailormap-components/projects/core/src/lib/shared/icon-picker/icon-picker.component.ts
  tailormap-components/projects/core/src/lib/shared/icons/icon.service.spec.ts
  tailormap-components/projects/core/src/lib/shared/icons/icon.service.ts
  tailormap-components/projects/core/src/lib/shared/shared.module.ts
Labels: viewer

#2225 Rename point label to pointsymbol
  tailormap-components/projects/core/src/lib/analysis/style-form/style-form.component.html
Labels: viewer

#2221 Rename 'kaartlaag' to 'selectielaag'
  tailormap-components/projects/core/src/lib/analysis/analysis-button/analysis-button.component.html
  tailormap-components/projects/core/src/lib/analysis/create-layer-panel/create-layer-panel.component.html
Labels: viewer

#2219 Feat/open form when cancelling geometry
  tailormap-components/projects/core/src/lib/shared/shared.module.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/layer.service.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/EditgeometryWorkflow.ts
Labels: viewer

#2220 Use Passport fields only when selecting attribute
  tailormap-components/projects/core/src/lib/analysis/attribute-selector/attribute-selector.component.html
  tailormap-components/projects/core/src/lib/analysis/attribute-selector/attribute-selector.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/attribute-selector/attribute-selector.component.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-mode-thematic/create-layer-mode-thematic.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria-description/criteria-description.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.ts
  tailormap-components/projects/core/src/lib/analysis/models/criteria-condition.model.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.actions.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.reducer.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.state.ts
  tailormap-components/projects/core/src/lib/application/models/passport-attribute.model.ts
  tailormap-components/projects/core/src/lib/application/services/metadata.service.ts
  tailormap-components/projects/core/src/lib/application/services/mocks/metadata.service.mock.ts
  tailormap-components/projects/core/src/lib/application/state/application.selectors.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form-models.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/linked-fields/domain-repository/domain-repository.service.ts
  tailormap-components/projects/core/src/lib/shared/formconfig-repository/formconfig-mock.module.spec.ts
  tailormap-components/projects/core/src/lib/shared/formconfig-repository/formconfig-repository.service.spec.ts
  tailormap-components/projects/core/src/lib/shared/formconfig-repository/formconfig-repository.service.ts
  tailormap-components/projects/core/src/lib/shared/tests/test-data.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-datasource.ts
Labels: viewer

#2222 WIP Feat/gbi martijn bugfixes
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.html
  tailormap-components/projects/core/src/lib/shared/attribute-service/attribute-models.ts
  tailormap-components/projects/core/src/lib/shared/value-service/value.service.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-datasource.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-filter.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-details/attributelist-details.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-filter-values-form/attributelist-filter-values-form.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tab-toolbar/attributelist-tab-toolbar.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tab-toolbar/attributelist-tab-toolbar.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-table/attributelist-table.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-table/attributelist-table.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tree/attributelist-tree-models.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tree/attributelist-tree.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tree/attributelist-tree.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist.service.ts
  viewer-config-persistence/src/test/java/nl/b3p/viewer/util/TestUtil.java
  viewer/src/main/java/nl/b3p/viewer/stripes/AttributesActionBean.java
  viewer/src/main/java/nl/b3p/viewer/util/FlamingoCQL.java
  viewer/src/test/java/nl/b3p/viewer/util/FlamingoCQLTest.java
Labels: viewer, viewer-config-persistence

#2232 Remove User Layer
  tailormap-components/projects/bridge/src/tailor-map.service.ts
  tailormap-components/projects/bridge/typings/Components.d.ts
  tailormap-components/projects/core/src/lib/analysis/analysis-button/analysis-button.component.css
  tailormap-components/projects/core/src/lib/analysis/analysis-button/analysis-button.component.html
  tailormap-components/projects/core/src/lib/analysis/analysis-button/analysis-button.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/analysis-button/analysis-button.component.ts
  tailormap-components/projects/core/src/lib/analysis/services/user-layer-api.service.ts
  tailormap-components/projects/core/src/lib/analysis/services/user-layer.service.ts
  tailormap-components/projects/core/src/lib/application/services/application.service.ts
  tailormap-components/projects/core/src/lib/application/state/application.actions.ts
  tailormap-components/projects/core/src/lib/application/state/application.effects.ts
  tailormap-components/projects/core/src/lib/application/state/application.reducer.ts
  tailormap-components/projects/core/src/lib/application/state/application.selectors.ts
  tailormap-components/projects/core/src/lib/application/state/application.state.ts
  tailormap-components/projects/core/src/lib/shared/tests/test-data.ts
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ViewerController.js
  viewer/src/main/webapp/viewer-html/components/TOC.js
Labels: viewer

#2238 reload table only if the feature clazz == table main feature clazz
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-datasource.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-table/attributelist-table.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist.service.ts
Labels: viewer

#2237 Feat/gbi disable relations when no related features
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tab-toolbar/attributelist-tab-toolbar.component.html
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tab-toolbar/attributelist-tab-toolbar.component.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-table/attributelist-table.component.ts
Labels: build infrastructure, viewer

#2239 dependency en CI updates
  .jenkins/start-oracle.sh
  Jenkinsfile
  pom.xml
  tomcat-lib/README.md
  tomcat-lib/pom.xml
  viewer-admin/pom.xml
  viewer-commons/pom.xml
  viewer-config-persistence/pom.xml
  viewer/pom.xml
Labels: backport v5.6.x, build infrastructure, viewer, viewer-admin, viewer-config-persistence

#2233 Bump geotools.version 24.1 ➜ 24.2 en b3p-commons-csw 6.3.1 ➜ 6.3.2
  pom.xml
Labels: dependencies, no backport :no_entry:

#2244 Add feature count to styling form
  tailormap-components/projects/bridge/src/tailor-map.service.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-form/create-layer-form.component.css
  tailormap-components/projects/core/src/lib/analysis/create-layer-form/create-layer-form.component.html
  tailormap-components/projects/core/src/lib/analysis/create-layer-mode-attributes/create-layer-mode-attributes.component.spec.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-mode-attributes/create-layer-mode-attributes.component.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-mode-thematic/create-layer-mode-thematic.component.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-panel/create-layer-panel.component.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-styling/create-layer-styling.component.css
  tailormap-components/projects/core/src/lib/analysis/create-layer-styling/create-layer-styling.component.html
  tailormap-components/projects/core/src/lib/analysis/create-layer-styling/create-layer-styling.component.ts
  tailormap-components/projects/core/src/lib/analysis/helpers/style.helper.ts
  tailormap-components/projects/core/src/lib/analysis/models/create-layer-data.model.ts
  tailormap-components/projects/core/src/lib/analysis/models/user-layer-style.model.ts
  tailormap-components/projects/core/src/lib/analysis/services/create-style.service.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.actions.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.effects.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.reducer.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.selectors.ts
  tailormap-components/projects/core/src/lib/analysis/state/analysis.state.ts
  tailormap-components/projects/core/src/lib/analysis/state/test-data/analysis-test-data.ts
  tailormap-components/projects/core/src/lib/application/services/metadata.service.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.spec.ts
  tailormap-components/projects/core/src/lib/shared/error-message/error-message.component.css
  tailormap-components/projects/core/src/lib/shared/error-message/error-message.component.html
  tailormap-components/projects/core/src/lib/shared/error-message/error-message.component.spec.ts
  tailormap-components/projects/core/src/lib/shared/error-message/error-message.component.ts
  tailormap-components/projects/core/src/lib/shared/formconfig-repository/formconfig-repository.service.spec.ts
  tailormap-components/projects/core/src/lib/shared/formconfig-repository/formconfig-repository.service.ts
  tailormap-components/projects/core/src/lib/shared/highlight-service/highlight.service.ts
  tailormap-components/projects/core/src/lib/shared/shared.module.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/layer.service.ts
  tailormap-components/projects/core/src/styles/styles.css
Labels: viewer

#2246 Owasp dep scanner updates
  .mvn/owasp-suppression.xml
  pom.xml
  viewer-config-persistence/src/main/resources/META-INF/persistence.xml
Labels: backport v5.6.x, build infrastructure, viewer-config-persistence

#2245 Feat/generic styled components
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.html
  tailormap-components/projects/core/src/lib/user-interface/generic-components/base-field/base-field.component.css
  tailormap-components/projects/core/src/lib/user-interface/generic-components/base-field/base-field.component.html
  tailormap-components/projects/core/src/lib/user-interface/generic-components/base-field/base-field.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/base-field/base-field.component.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/input-field/input-field.component.css
  tailormap-components/projects/core/src/lib/user-interface/generic-components/input-field/input-field.component.html
  tailormap-components/projects/core/src/lib/user-interface/generic-components/input-field/input-field.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/input-field/input-field.component.ts
  tailormap-components/projects/core/src/lib/user-interface/user-interface.module.ts
Labels: viewer

#2249 add missing selectedcontentcaches_dirty for MS SQL Server
  viewer-config-persistence/src/main/resources/scripts/microsoft_sql_server-selectedcontentcaches_dirty.sql
Labels: :bomb: bug, backport v5.6.x, viewer-config-persistence

#2281 Update actions/cache requirement to v2, bump actions/setup-node from v1 to v2
  .github/workflows/angular-components-deployment.yml
  .github/workflows/angular-components.yml
  .github/workflows/backport.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/macos-maven.yml
  .github/workflows/ubuntu-maven.yml
Labels: build infrastructure

#2280 dependency management van Jackson 2 libs
  .github/dependabot.yml
  form/pom.xml
  form/src/main/java/nl/b3p/gbi/converter/Formulier.java
  form/src/main/java/nl/b3p/gbi/converter/FormulierTabConfig.java
  form/src/main/java/nl/b3p/gbi/converter/Parser.java
  form/src/main/java/nl/b3p/gbi/converter/Paspoort.java
  form/src/main/java/nl/b3p/gbi/converter/PaspoortTab.java
  form/src/main/java/nl/b3p/gbi/converter/TabConfigSerializer.java
  pom.xml
  tailormap-components/package.json
Labels: build infrastructure, dependencies, no backport :no_entry:, security, viewer

#2285 Adds stylelint
  tailormap-components/.stylelintrc.json
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/bridge/src/styles.css
  tailormap-components/projects/core/src/lib/analysis/create-layer-panel/create-layer-panel.component.css
  tailormap-components/projects/core/src/lib/analysis/create-layer-styling/create-layer-styling.component.css
  tailormap-components/projects/core/src/lib/analysis/criteria/advanced-criteria/advanced-criteria.component.css
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria-group/criteria-group.component.css
  tailormap-components/projects/core/src/lib/application/style/application-tree.css
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree.component.css
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.css
  tailormap-components/projects/core/src/lib/shared/color-picker/color-picker.component.css
  tailormap-components/projects/core/src/lib/shared/icon-picker/icon-picker.component.css
  tailormap-components/projects/core/src/lib/shared/tree/style/tree-node-style.css
  tailormap-components/projects/core/src/lib/shared/tree/tree.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-details/attributelist-details.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-filter-values-form/attributelist-filter-values-form.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-form/attributelist-form.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-panel/attributelist-panel.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tab-toolbar/attributelist-tab-toolbar.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-tab/attributelist-tab.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-table-options-form/attributelist-table-options-form.component.css
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-table/attributelist-table.component.css
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/add-feature-menu/menu-button/menu-button.component.css
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/edit-bar/edit-bar.component.css
  tailormap-components/projects/core/src/lib/user-interface/geometry-confirm-buttons/geometry-confirm-buttons.component.css
  tailormap-components/projects/core/src/lib/user-interface/panel-resizer/panel-resizer.component.css
  tailormap-components/projects/core/src/lib/user-interface/sewage/choose-types/choose-types.component.css
  tailormap-components/projects/core/src/lib/workflow/workflow-controller/workflow-controller.component.css
  tailormap-components/projects/core/src/styles/inter-font.css
  tailormap-components/projects/core/src/styles/styles.css
Labels: viewer

#2287 stylelint checker
  .github/workflows/angular-components.yml
Labels: build infrastructure

#2291 [Backport v5.6.x] Bump maven-surefire-plugin.version from 3.0.0-M4 to 3.0.0-M5
  pom.xml
Labels: build infrastructure

#2292 [Backport v5.4.x] Bump maven-surefire-plugin.version from 3.0.0-M4 to 3.0.0-M5
  pom.xml
Labels: build infrastructure

#2290 Adds translate and rotate feature options to the Edit component
  viewer-admin/src/main/resources/ViewerResources.properties
  viewer-admin/src/main/resources/ViewerResources_en.properties
  viewer/src/main/resources/ViewerResources.properties
  viewer/src/main/resources/ViewerResources_en.properties
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/OlVectorLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersVectorLayer.js
  viewer/src/main/webapp/viewer-html/components/Edit-config.js
  viewer/src/main/webapp/viewer-html/components/Edit.js
Labels: enhancement :+1:, featurerequest :+1:, no backport :no_entry:, viewer, viewer-admin

#2286 CI/CD only triggers workflows for its intended jobs
  .github/workflows/angular-components-deployment.yml
  .github/workflows/angular-components.yml
  .github/workflows/macos-maven.yml
  .github/workflows/ubuntu-maven.yml
  appveyor.yml
  tailormap-components/projects/core/src/lib/workflow/workflows/EditgeometryWorkflow.ts
Labels: build infrastructure, viewer

#2294 Make it possible to draw 90 degree angle while editing when the S key is held down
  viewer/src/main/webapp/viewer-html/common/viewercontroller/controller/VectorLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/ol/OlVectorLayer.js
  viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersVectorLayer.js
Labels: enhancement :+1:, featurerequest :+1:, viewer

#2295 Update Spectator to support Angular 11
  pom.xml
  tailormap-components/package-lock.json
  tailormap-components/package.json
Labels: dependencies, viewer
