Repository B3Partners/tailormap, pull requests merged in 2021-06, with the labels that each got.

#2712 [TM-180] stoppen met integratie testen tegen Oracle
  .github/workflows/owasp-dependency-check.yml
  .github/workflows/ubuntu-maven.yml
  .jenkins/clear-oracle-schema.sql
  .jenkins/create_oracle_user.sql
  .jenkins/insert-fla-version.sh
  .jenkins/start-oracle.sh
  Jenkinsfile
  pom.xml
  viewer-admin/pom.xml
  viewer-admin/src/test/resources/oracle.properties
  viewer-admin/src/test/tomcatconf/jenkinscontext.xml
  viewer/pom.xml
  viewer/src/test/java/nl/viewer/stripes/UserLayerActionBeanIntegrationTest.java
  viewer/src/test/java/nl/viewer/userlayer/OracleIntegrationTest.java
  viewer/src/test/resources/oracle.properties
  viewer/src/test/tomcatconf/jenkinscontext.xml
Labels: build infrastructure, no backport :no_entry:, viewer, viewer-admin

#2714 Upgrade to Angular 12, NgRx 12
  tailormap-components/angular.json
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/bridge/src/environments/environment.ts
  tailormap-components/projects/bridge/src/polyfills.ts
  tailormap-components/projects/bridge/src/test.ts
  tailormap-components/projects/core/src/styles/custom-theme.scss
  tailormap-components/projects/core/src/test.ts
Labels: no backport :no_entry:, viewer

#2716 Retrieve layer based on correct layername. Fixes TM-196
  viewer-helpers/src/main/java/nl/viewer/helpers/services/WMSServiceHelper.java
Labels: :bomb: bug, no backport :no_entry:

#2718 Upgrade Angular version to 12.0.3
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/core/src/lib/shared/helpers/attribute-filter.helper.ts
  tailormap-components/projects/core/src/lib/workflow/workflow-controller/workflow-models.ts
Labels: viewer

#2717 add build dev and prod to ci/cd
  .github/workflows/angular-components.yml
Labels: build infrastructure, no backport :no_entry:

#2713 [TM-216] Feat/cleanup gbi references
  tailormap-components/projects/core/src/lib/application/helpers/feature.helper.ts
  tailormap-components/projects/core/src/lib/application/state/application.selectors.ts
  tailormap-components/projects/core/src/lib/feature-form/form-actions/form-actions.service.ts
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/services/edit-feature-geometry.service.ts
  tailormap-components/projects/core/src/lib/shared/feature-initializer/feature-initializer-models.ts
  tailormap-components/projects/core/src/lib/shared/feature-initializer/feature-initializer.service.mock.ts
  tailormap-components/projects/core/src/lib/shared/feature-initializer/feature-initializer.service.spec.ts
  tailormap-components/projects/core/src/lib/shared/feature-initializer/feature-initializer.service.ts
  tailormap-components/projects/core/src/lib/shared/formconfig-repository/form-config-repository.service.ts
  tailormap-components/projects/core/src/lib/shared/generated/index.ts
  tailormap-components/projects/core/src/lib/shared/generated/models.ts
  tailormap-components/projects/core/src/lib/shared/generated/models/feature.ts
  tailormap-components/projects/core/src/lib/shared/generated/models/featuretype-metadata.ts
  tailormap-components/projects/core/src/lib/shared/generated/models/field.ts
  tailormap-components/projects/core/src/lib/shared/tests/test-data.ts
  tailormap-components/projects/core/src/lib/user-interface/attributelist/attribute-list-tab-toolbar/attribute-list-tab-toolbar.component.ts
  tailormap-components/projects/core/src/lib/user-interface/edit-bar/add-feature-menu/add-feature-menu.component.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/SewageWorkflow.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/StandardFormWorkflow.ts
Labels: viewer

#2724 Include empty CSS file so customer CSS can be included from deployment
  viewer/src/main/webapp/WEB-INF/jsp/app.jsp
  viewer/src/main/webapp/WEB-INF/jsp/templates/ext.jsp
  viewer/src/main/webapp/about.jsp
  viewer/src/main/webapp/resources/css/custom_style.css
Labels: backport v5.8.x, viewer

#2734 Bump dependency-check-maven from 6.2.1 to 6.2.2
  pom.xml
Labels: build infrastructure

#2601 Use Tomcat 9 for integratie tests, drop SQL Server tests, drop AppVeyor, use Github runner for Windows as well
  .appveyor/set-maven-proxy.ps1
  .github/dependabot.yml
  .github/workflows/macos-maven.yml
  .github/workflows/windows-maven.yml
  README.md
  appveyor.yml
  pom.xml
  tailormap-components/package-lock.json
  viewer-admin/pom.xml
  viewer-admin/src/main/java/nl/tailormap/viewer/admin/monitoring/GeoServiceMonitoringListener.java
  viewer-admin/src/main/webapp/META-INF/context.xml
  viewer-admin/src/test/resources/ms_sql_server.properties
  viewer-admin/src/test/tomcatconf/appveyorcontext.xml
  viewer-admin/src/test/tomcatconf/context.xml
  viewer/pom.xml
  viewer/src/main/webapp/META-INF/context.xml
  viewer/src/test/java/nl/tailormap/viewer/ViewerIntegrationTest.java
  viewer/src/test/java/nl/tailormap/viewer/userlayer/SQLServerIntegrationTest.java
  viewer/src/test/resources/ms_sql_server.properties
  viewer/src/test/resources/postgres.properties
  viewer/src/test/tomcatconf/appveyorcontext.xml
  viewer/src/test/tomcatconf/context.xml
Labels: build infrastructure, java11, no backport :no_entry:, security, viewer, viewer-admin

#2747 TM-10 added checkboxes and date types for form-field
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form-models.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/base-field/base-field.component.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/datepicker-field/datepicker-field.component.css
  tailormap-components/projects/core/src/lib/user-interface/generic-components/datepicker-field/datepicker-field.component.html
  tailormap-components/projects/core/src/lib/user-interface/generic-components/datepicker-field/datepicker-field.component.spec.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/datepicker-field/datepicker-field.component.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/input-field/input-field.component.ts
  tailormap-components/projects/core/src/lib/user-interface/generic-components/label-field/label-field.component.css
  tailormap-components/projects/core/src/lib/user-interface/generic-components/label-field/label-field.component.html
  tailormap-components/projects/core/src/lib/user-interface/generic-components/label-field/label-field.component.ts
  tailormap-components/projects/core/src/lib/user-interface/user-interface.module.ts
Labels: enhancement :+1:, viewer

#2748 TM-45: Only show editable layers as datasource for userlayer
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/bridge/typings/Mapcomponents.d.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-layer-selection/create-layer-layer-selection.component.ts
  tailormap-components/projects/core/src/lib/application/application-tree-node/application-tree-node.component.css
  tailormap-components/projects/core/src/lib/application/state/application.selectors.ts
  tailormap-components/projects/core/src/lib/shared/layer-utils/layer-utils.service.spec.ts
  tailormap-components/projects/core/src/lib/shared/tests/test-data.ts
Labels: viewer

#2750 TM-167: Fix creating user layer with related filter
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.ts
  tailormap-components/projects/core/src/lib/shared/helpers/attribute-filter.helper.ts
Labels: viewer

#2749 TM-164: Retrieve unique values with filter
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/core/src/lib/application/services/application.service.ts
  tailormap-components/projects/core/src/lib/application/services/metadata.service.ts
  tailormap-components/projects/core/src/lib/shared/tests/test-data.ts
Labels: viewer

#2746 Simplified setting name of table/featuretype in formconfig
  form/src/main/java/nl/tailormap/gbi/converter/Converter.java
  tailormap-components/projects/core/src/lib/analysis/state/test-data/analysis-test-data.ts
  tailormap-components/projects/core/src/lib/application/state/application.selectors.ts
  tailormap-components/projects/core/src/lib/feature-form/form-attribute-list-button/form-attribute-list-button.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/linked-fields/domain-repository/domain-repository.service.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.selectors.ts
  tailormap-components/projects/core/src/lib/shared/feature-initializer/feature-initializer.service.ts
  tailormap-components/projects/core/src/lib/shared/feature-selection/feature-selection.component.ts
  tailormap-components/projects/core/src/lib/shared/formconfig-repository/form-config-repository.service.ts
  tailormap-components/projects/core/src/lib/shared/layer-utils/layer-utils.service.spec.ts
  tailormap-components/projects/core/src/lib/shared/layer-utils/layer-utils.service.ts
Labels: viewer

#2751 Fixes double instances of services + fixes layer visibility changes
  tailormap-components/package.json
  tailormap-components/projects/core/src/lib/analysis/analysis-attribute-list-button/analysis-attribute-list-button.component.ts
  tailormap-components/projects/core/src/lib/analysis/attribute-selector/attribute-selector.component.ts
  tailormap-components/projects/core/src/lib/analysis/create-layer-layer-selection/create-layer-layer-selection.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria-description/criteria-description.component.ts
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria/criteria.component.ts
  tailormap-components/projects/core/src/lib/analysis/services/create-style.service.ts
  tailormap-components/projects/core/src/lib/application/services/application.service.ts
  tailormap-components/projects/core/src/lib/application/services/metadata.service.ts
  tailormap-components/projects/core/src/lib/application/services/mocks/metadata.service.mock.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
Labels: viewer

#2752 Bug/change clazz to tablename
  tailormap-components/projects/core/src/lib/feature-form/form-actions/form-actions.service.ts
  tailormap-components/projects/core/src/lib/feature-form/form-attribute-list-button/form-attribute-list-button.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.spec.ts
  tailormap-components/projects/core/src/lib/feature-form/form-copy/form-copy.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-field/formfield.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/services/edit-feature-geometry.service.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.selectors.ts
  tailormap-components/projects/core/src/lib/shared/feature-initializer/feature-initializer.service.ts
  tailormap-components/projects/core/src/lib/shared/feature-selection/feature-selection.component.ts
  tailormap-components/projects/core/src/lib/shared/generated/models/feature.ts
  tailormap-components/projects/core/src/lib/shared/tests/test-data.ts
  tailormap-components/projects/core/src/lib/workflow/workflows/CopyWorkflow.ts
Labels: viewer

#2754 testdata fixed
  tailormap-components/projects/core/src/lib/shared/layer-utils/layer-utils.service.spec.ts
  tailormap-components/projects/core/src/lib/shared/tests/test-data.ts
Labels: viewer

#2759 Prevent application from crashing if formconfig is not found
  tailormap-components/projects/core/src/lib/feature-form/form-tree/form-tree-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.css
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.html
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
Labels: viewer
