Repository B3Partners/tailormap, pull requests merged in 2022-02, with the labels that each got.

#3079 [5.6.x] Bump postgresql and oracle drivers (security fix)
  pom.xml
Labels: security, dependencies

#3078 [5.8.x] Bump postgresql and oracle drivers (security fix)
  pom.xml
Labels: security, dependencies

#3080 GBIM-257: Use CQL for attribute list if there is an external filter set
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/core/src/lib/analysis/criteria/criteria-description/criteria-description.component.ts
  tailormap-components/projects/core/src/lib/analysis/services/create-style.service.ts
  tailormap-components/projects/core/src/lib/application/services/application.service.ts
  tailormap-components/projects/core/src/lib/application/services/metadata.service.ts
Labels: viewer

#3084 GBIM-251: tableName can only be 23 chars max
  viewer/src/main/java/nl/tailormap/viewer/userlayer/UserLayerHandler.java
Labels: bug, viewer

#3090 GBIM-299 & GBIM-300
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/core/src/lib/application/state/application.actions.ts
  tailormap-components/projects/core/src/lib/feature-form/form-actions/form-actions.service.ts
  tailormap-components/projects/core/src/lib/feature-form/form-attribute-list-button/form-attribute-list-button.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-attribute-list-button/form-attribute-list-button.component.ts
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.css
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.html
  tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.actions.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.effects.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.reducer.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.selectors.ts
  tailormap-components/projects/core/src/lib/feature-form/state/form.state.ts
  tailormap-components/projects/core/src/lib/shared/generated/services/feature-controller.service.ts
Labels: viewer

#3105 Dependency updates 5.6.x
  pom.xml
Labels: security, dependencies

#3104 Dependency updates 5.8.x
  pom.xml
Labels: security, dependencies

#3111 Bump GeoTools 25.4 -> 25.5
  pom.xml
Labels: dependencies

#3107 stop looking for more relations if tail is equals to head
  viewer-helpers/src/main/java/nl/tailormap/viewer/helpers/app/ApplicationLayerHelper.java
Labels: enhancement, viewer

#3112 GBIM-239: Changed warning message when removing object with relations
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/core/src/lib/feature-form/form/form-helpers.ts
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
Labels: viewer
