Repository B3Partners/tailormap, pull requests merged in 2022-05, with the labels that each got.

#3233 Fix layercount
  viewer-helpers/src/test/java/nl/tailormap/viewer/config/services/TileServiceTest.java
Labels: bug, build infrastructure, backport v5.6.x, backport v5.8.x

#3245 GBIM-332: Fixes switching between forms
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.html
  tailormap-components/projects/core/src/lib/feature-form/form/form.component.ts
  tailormap-components/projects/core/src/lib/feature-form/linked-fields/registry/linked-attribute-registry.service.ts
Labels: bug, viewer

#3238 Upgrade GeoTools 26.x ➜ 27.x
  pom.xml
Labels: dependencies, no backport :no_entry:
