Repository B3Partners/tailormap, pull requests merged in 2022-06, with the labels that each got.

#3267 Update various Maven plugins and dependencies
  pom.xml
Labels: build infrastructure, dependencies

#3256 GBIM-331: Updated packages + fixed models
  tailormap-components/package-lock.json
  tailormap-components/package.json
  tailormap-components/projects/core/src/lib/analysis/criteria/helpers/criteria.helper.ts
Labels: bug, viewer

#3299 Build infra updates
  .github/dependabot.yml
  .github/workflows/macos-maven.yml
  .github/workflows/owasp-dependency-check.yml
  .github/workflows/ubuntu-maven.yml
  Jenkinsfile
  pom.xml
Labels: build infrastructure, no backport :no_entry:, java11

#3300 Dependency updates
  pom.xml
  viewer-config-persistence/pom.xml
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/ArcGISService.java
  viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/WMSService.java
Labels: dependencies, viewer-config-persistence
